/**
 * Medieval-Europe content pack — FIXTURE TYPE catalogue.
 *
 * Pure data. No logic. Each entry is one `FactEntry<FixtureTypeFields>` describing
 * a fixed installation found inside (or piercing) medieval buildings: hearths,
 * smoke-egress systems, work fittings, church furnishings, lighting, etc.
 *
 * COUPLING CONTRACT (other engine code keys off these exact tokens/ids):
 *   - Hearth fixtures EMIT the requirement token 'smoke-egress':
 *       open-hearth (centre), wall-fireplace (wall), inglenook (wall)
 *   - Smoke-egress fixtures SATISFY 'smoke-egress':
 *       smoke-hole, louver, smoke-hood (ridge) and wall-chimney (wall)
 *     Historical availability is encoded in `applicability.eras` (and wealth for
 *     the late, elite wall-chimney). The early-medieval default is the smoke-hole
 *     / louver; the chimney is a late + rich upgrade.
 */
import type { FactEntry, FixtureTypeFields } from '@/catalogue/types';

export const MEDIEVAL_FIXTURE_TYPES: FactEntry<FixtureTypeFields>[] = [
  // ── HEARTHS (emit 'smoke-egress') ─────────────────────────────────────────
  {
    id: 'open-hearth',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['primordial', 'ancient', 'classical', 'medieval'] },
    lod: {
      l0: 'A central open fire on the floor of the hall.',
      l1: ['ring of stones', 'ash bed', 'low flames', 'soot-blackened rafters above'],
      l2: 'The defining heat-and-light source of the early hall: an open fire kindled directly on a stone-edged patch of the floor, set centrally so people sit around it. Smoke rises freely to the roof and escapes through a vent, so the rafters and underside of the thatch are tarred black. It heats the whole single space but ties the building to an unceiled, open-to-the-roof plan.',
    },
    fields: { requires: ['smoke-egress'], placement: 'centre' },
    provenance: ['https://en.wikipedia.org/wiki/Fireplace'],
    visibility: 'data-only',
    tags: ['hearth', 'fire', 'heating'],
  },
  {
    id: 'hearthstone',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['primordial', 'ancient', 'classical', 'medieval', 'current'] },
    lod: {
      l0: 'The flat stone slab a fire is laid upon.',
      l1: ['single broad flagstone', 'fire-cracked and reddened', 'set flush with the floor'],
      l2: 'A large flat stone bedded into the floor (or the base of a fireplace) on which the fire is built, protecting the floor and storing heat. Symbolic centre of the home — the word "hearth" stands for the household itself.',
    },
    fields: { satisfies: ['fire-base'], placement: 'centre' },
    visibility: 'data-only',
    tags: ['hearth', 'fire', 'stone'],
  },
  {
    id: 'wall-fireplace',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['medieval', 'current'], wealth: ['comfortable', 'rich', 'opulent'] },
    lod: {
      l0: 'A fire recessed into a wall and drawn off by a flue.',
      l1: ['stone or brick surround', 'arched or lintelled opening', 'masonry breast above'],
      l2: 'A fire moved off the floor and set into the thickness of a wall, with a built breast and flue carrying the smoke up and out. Frees the centre of the room and allows an upper floor to be ceiled over, but is costly masonry — at first a feature of castles and grand houses before spreading down the wealth ladder.',
    },
    fields: { requires: ['smoke-egress'], placement: 'wall' },
    provenance: ['https://en.wikipedia.org/wiki/Fireplace'],
    visibility: 'data-only',
    tags: ['hearth', 'fire', 'heating', 'masonry'],
  },
  {
    id: 'inglenook',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['medieval', 'current'], wealth: ['comfortable', 'rich'] },
    lod: {
      l0: 'A deep recessed alcove around a wall fire, with seating.',
      l1: ['wide cavernous opening', 'built-in benches inside', 'heavy timber bressummer beam', 'pothooks overhead'],
      l2: 'A large recess adjoining a fireplace — a "chimney corner" deep enough to step into and sit beside the fire, sheltered from draughts. Often holds built-in benches, salt cupboards and a bread oven in its cheeks. A comfort feature of the larger late-medieval farmhouse and tavern.',
    },
    fields: { requires: ['smoke-egress'], placement: 'wall' },
    provenance: ['https://en.wikipedia.org/wiki/Inglenook'],
    visibility: 'data-only',
    tags: ['hearth', 'fire', 'seating', 'comfort'],
  },

  // ── SMOKE EGRESS (satisfy 'smoke-egress') ─────────────────────────────────
  {
    id: 'smoke-hole',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['primordial', 'ancient', 'classical', 'medieval'] },
    lod: {
      l0: 'A simple gap in the roof apex that lets smoke out.',
      l1: ['open hole at the ridge', 'soot-stained edges', 'no cover'],
      l2: 'The most primitive smoke vent: an unglazed, uncovered opening left in the apex of the roof above the open hearth. Smoke drifts up and out (and rain drifts in). Universal in the earliest dwellings; pierces the roof, so it reads on the exterior silhouette.',
    },
    fields: { satisfies: ['smoke-egress'], placement: 'ridge' },
    provenance: ['https://en.wikipedia.org/wiki/Fireplace'],
    visibility: 'geometry',
    tags: ['smoke', 'vent', 'roof'],
  },
  {
    id: 'louver',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['medieval'] },
    lod: {
      l0: 'A slatted roof lantern that vents smoke while shedding rain.',
      l1: ['raised turret on the ridge', 'angled timber slats', 'sometimes a small finial cap'],
      l2: 'A purpose-built smoke vent over the central hearth of a hall: a small raised structure on the ridge with sloping slats (and sometimes louvre-boards that could be turned to the wind) that let smoke escape while keeping out rain. The dressed, lantern-like version of the smoke-hole; a recognisable feature of the medieval great hall roofline.',
    },
    fields: { satisfies: ['smoke-egress'], placement: 'ridge' },
    provenance: ['https://en.wikipedia.org/wiki/Fireplace', 'https://en.wikipedia.org/wiki/Louver'],
    visibility: 'geometry',
    tags: ['smoke', 'vent', 'roof', 'hall'],
  },
  {
    id: 'smoke-hood',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['medieval'] },
    lod: {
      l0: 'A wide canopy funnelling hearth smoke up to a ridge vent.',
      l1: ['broad timber-and-plaster hood', 'tapering canopy', 'rises to a roof outlet'],
      l2: 'A large hood of timber, wattle and daub (or plaster) suspended over a hearth set against or near a wall, catching the smoke and funnelling it up to an outlet at the ridge. A transitional device between the open hearth and the masonry chimney — cheaper than building a stone flue but a real improvement in clearing smoke.',
    },
    fields: { satisfies: ['smoke-egress'], placement: 'ridge' },
    provenance: ['https://en.wikipedia.org/wiki/Fireplace'],
    visibility: 'geometry',
    tags: ['smoke', 'vent', 'roof', 'transitional'],
  },
  {
    id: 'wall-chimney',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['medieval', 'current'], wealth: ['rich', 'opulent'] },
    lod: {
      l0: 'A masonry flue carrying smoke up through a wall and out a stack.',
      l1: ['tall brick or stone stack', 'projecting breast', 'capped chimney pot or coping'],
      l2: 'A built flue of brick or stone enclosing the path of the smoke from a wall fireplace up through the building and out above the roof. Late and expensive: chimneys appear first in castles and grand houses and only slowly become an ordinary upgrade. A no-vent or open-hearth building should NOT get a chimney by default — it is the elite, late option on the smoke-egress ladder. Pierces and rises above the roof, so it dominates the silhouette.',
    },
    fields: { satisfies: ['smoke-egress'], placement: 'wall' },
    provenance: ['https://en.wikipedia.org/wiki/Fireplace', 'https://en.wikipedia.org/wiki/Chimney'],
    visibility: 'geometry',
    tags: ['smoke', 'chimney', 'masonry', 'elite', 'late'],
  },

  // ── COOKING & DOMESTIC FITTINGS ───────────────────────────────────────────
  {
    id: 'bread-oven',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['classical', 'medieval', 'current'] },
    lod: {
      l0: 'A domed masonry oven heated by a fire then baked clean.',
      l1: ['beehive-shaped brick dome', 'small arched mouth', 'iron door or stone slab', 'sometimes built into a chimney cheek'],
      l2: 'A small domed oven of brick, clay or stone in which a fire is lit to soak the masonry with heat, then raked out before the dough goes in to bake on the retained heat. Set into the side of an inglenook, a bakehouse, or built free-standing; a village often shared a common oven.',
    },
    fields: { requires: ['smoke-egress'], placement: 'wall' },
    visibility: 'data-only',
    tags: ['oven', 'baking', 'masonry', 'food'],
  },
  {
    id: 'forge-hearth',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['classical', 'medieval', 'current'] },
    lod: {
      l0: 'A blast hearth for heating iron to working temperature.',
      l1: ['raised brick or stone bed', 'glowing charcoal', 'tuyere for the bellows blast', 'overhanging smoke hood'],
      l2: 'The heart of the smithy: a raised hearth burning charcoal forced to white heat by an air blast from the bellows, where iron is brought to forging temperature. Throws great heat and smoke, so it sits under a hood and against a wall.',
    },
    fields: { requires: ['smoke-egress'], placement: 'wall' },
    visibility: 'data-only',
    tags: ['forge', 'smithy', 'fire', 'metalwork'],
  },
  {
    id: 'anvil',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['classical', 'medieval', 'current'] },
    lod: {
      l0: 'A heavy iron block on which hot metal is hammered.',
      l1: ['flat working face', 'tapering horn', 'hardy hole', 'mounted on a timber stump'],
      l2: 'A massive block of iron (latterly steel-faced) bedded on a stout timber stump near the forge, providing the unyielding surface against which the smith shapes heated metal with the hammer. The horn gives curves; the hardy and pritchel holes hold tools.',
    },
    fields: { placement: 'centre' },
    visibility: 'data-only',
    tags: ['forge', 'smithy', 'tool', 'metalwork'],
  },
  {
    id: 'bellows',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['classical', 'medieval', 'current'] },
    lod: {
      l0: 'A pumped leather-and-board device that blasts air into a fire.',
      l1: ['hinged wooden boards', 'pleated leather bag', 'nozzle aimed at the hearth', 'often a great lever or treadle'],
      l2: 'Paired boards joined by a pleated leather chamber that, worked by hand, lever or water power, drive a stream of air through a tuyere into the forge or furnace to raise its temperature. Large smithies and bloomeries used great bellows worked by an apprentice or a waterwheel.',
    },
    fields: { satisfies: ['forge-draught'], placement: 'wall' },
    visibility: 'data-only',
    tags: ['forge', 'smithy', 'tool', 'air'],
  },
  {
    id: 'pothook',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['ancient', 'classical', 'medieval', 'current'] },
    lod: {
      l0: 'An adjustable hook hanging a cauldron over the fire.',
      l1: ['iron ratchet or chain', 'swinging crane arm', 'heavy cooking pot suspended'],
      l2: 'An iron hook, ratcheted bar or swinging crane fixed above the hearth from which the cooking cauldron is hung, letting the cook raise or lower the pot over the flames. The basic apparatus of open-hearth cookery.',
    },
    fields: { placement: 'centre' },
    visibility: 'data-only',
    tags: ['hearth', 'cooking', 'iron', 'food'],
  },

  // ── BREWING & DAIRY & FOOD PROCESSING ─────────────────────────────────────
  {
    id: 'brewing-copper',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['medieval', 'current'] },
    lod: {
      l0: 'A great fixed copper vessel for boiling the brew.',
      l1: ['large beaten-copper vat', 'set over its own firebox', 'steam and a wooden lid'],
      l2: 'A large copper (or bronze) cauldron set in masonry over a fire, used to heat liquor and boil the wort with hops in brewing. A fixed, expensive fitting that marks a brewhouse or a tavern that brews its own ale.',
    },
    fields: { requires: ['smoke-egress'], placement: 'corner' },
    visibility: 'data-only',
    tags: ['brewing', 'ale', 'copper', 'fire'],
  },
  {
    id: 'mash-tun',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['medieval', 'current'] },
    lod: {
      l0: 'A large wooden tub where malt steeps in hot water.',
      l1: ['broad coopered tub', 'iron-hooped staves', 'false bottom for draining', 'wooden lid'],
      l2: 'A big coopered vessel in which crushed malt is mixed with hot water so the grain releases its sugars, then the sweet wort is run off. The first vessel of the brewing sequence; stands beside the copper in a brewhouse.',
    },
    fields: { placement: 'corner' },
    visibility: 'data-only',
    tags: ['brewing', 'ale', 'cooperage'],
  },
  {
    id: 'malt-kiln',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['medieval', 'current'] },
    lod: {
      l0: 'A floored kiln that dries and lightly roasts sprouted grain.',
      l1: ['perforated drying floor', 'gentle fire beneath', 'haircloth or tile bed', 'low smoky heat'],
      l2: 'A kiln where germinated barley (green malt) is dried and cured over a low fire to halt sprouting and develop colour and flavour. The fuel smoke can flavour the malt, so a malthouse vents the kiln carefully.',
    },
    fields: { requires: ['smoke-egress'], placement: 'corner' },
    visibility: 'data-only',
    tags: ['brewing', 'malt', 'kiln', 'fire'],
  },
  {
    id: 'cheese-press',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['ancient', 'classical', 'medieval', 'current'] },
    lod: {
      l0: 'A weighted press that squeezes whey from curds.',
      l1: ['timber frame', 'screw or lever and stone weight', 'draining board and moulds'],
      l2: 'A frame in which cheese moulds full of curd are pressed under a heavy stone or screw to expel the whey and consolidate the cheese. A standard fitting of the dairy.',
    },
    fields: { placement: 'corner' },
    visibility: 'data-only',
    tags: ['dairy', 'cheese', 'press', 'food'],
  },
  {
    id: 'salting-trough',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['ancient', 'classical', 'medieval', 'current'] },
    lod: {
      l0: 'A stone or timber trough for salting and curing meat.',
      l1: ['hollowed stone or lined wooden trough', 'salt crust', 'sometimes a lid or weighting board'],
      l2: 'A trough in which joints of meat or fish are packed in salt (or brine) to cure them for winter storage. A larder or kitchen fixture; the chief means of preserving protein before refrigeration.',
    },
    fields: { placement: 'corner' },
    visibility: 'data-only',
    tags: ['larder', 'preservation', 'meat', 'food'],
  },
  {
    id: 'quern',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['primordial', 'ancient', 'classical', 'medieval'] },
    lod: {
      l0: 'A pair of hand-turned stones for grinding grain at home.',
      l1: ['two round flat stones', 'central feed hole', 'wooden turning handle', 'meal collecting around the rim'],
      l2: 'A rotary hand-mill: an upper stone turned by hand on a fixed lower stone to grind grain into flour or meal. The domestic mill of the household — though lords often forbade them to force tenants to the manorial watermill and pay the multure.',
    },
    fields: { satisfies: ['grain-milling'], placement: 'corner' },
    provenance: ['https://en.wikipedia.org/wiki/Quern-stone'],
    visibility: 'data-only',
    tags: ['milling', 'grain', 'stone', 'food'],
  },
  {
    id: 'millstone',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['classical', 'medieval', 'current'] },
    lod: {
      l0: 'A large dressed grinding stone driven by water or wind power.',
      l1: ['great circular stone', 'radial dressing furrows', 'central eye', 'paired runner over bedstone'],
      l2: 'A massive paired grinding stone (runner over bedstone), its faces cut with radial furrows, driven by the mill\'s gearing to grind grain in bulk. The working heart of a watermill or windmill.',
    },
    fields: { satisfies: ['grain-milling'], placement: 'centre' },
    provenance: ['https://en.wikipedia.org/wiki/Millstone'],
    visibility: 'data-only',
    tags: ['milling', 'grain', 'stone', 'mechanism'],
  },
  {
    id: 'water-wheel',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['classical', 'medieval', 'current'] },
    lod: {
      l0: 'A water-driven wheel powering a mill\'s machinery.',
      l1: ['large spoked wheel', 'paddles or buckets on the rim', 'mounted in a race', 'dripping and turning'],
      l2: 'A great wheel turned by a stream — undershot, overshot or breast-shot — whose rotation is geared to drive millstones, bellows, fulling stocks or hammers. Pierces the building line on its mill-race side, so part of it shows on the exterior.',
    },
    fields: { satisfies: ['mechanical-power'], placement: 'wall' },
    provenance: ['https://en.wikipedia.org/wiki/Water_wheel'],
    visibility: 'geometry',
    tags: ['mill', 'water', 'power', 'mechanism'],
  },

  // ── ANIMAL & AGRICULTURAL FITTINGS ────────────────────────────────────────
  {
    id: 'manger',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['ancient', 'classical', 'medieval', 'current'] },
    lod: {
      l0: 'A trough holding fodder for stalled animals.',
      l1: ['long timber or stone trough', 'fixed along the byre wall', 'hayrack above'],
      l2: 'A feeding trough fixed along the wall of a byre or stable, filled with hay or fodder for the stalled cattle or horses, often with a rack above. The defining fitting of the animal end of a longhouse or barn.',
    },
    fields: { placement: 'wall' },
    visibility: 'data-only',
    tags: ['byre', 'stable', 'animal', 'feeding'],
  },
  {
    id: 'byre-drain',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['ancient', 'classical', 'medieval', 'current'] },
    lod: {
      l0: 'A floor channel carrying animal waste out of the byre.',
      l1: ['stone-lined gutter behind the stalls', 'sloped to one end', 'outlet through the lower wall'],
      l2: 'A channel cut or laid in the byre floor behind the standing animals, sloped to drain urine and washings out through the downhill gable — which is why the animal end of a longhouse sits at the lower end of the slope.',
    },
    fields: { satisfies: ['waste-drainage'], placement: 'floor' },
    visibility: 'data-only',
    tags: ['byre', 'animal', 'drainage', 'longhouse'],
  },
  {
    id: 'dung-drain',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['ancient', 'classical', 'medieval', 'current'] },
    lod: {
      l0: 'A drain leading dung and slurry to a midden outside.',
      l1: ['gutter through the wall foot', 'leads to an external midden pit', 'sometimes a soak-away'],
      l2: 'The outfall side of byre and yard drainage: a drain running waste and slurry out to a dung heap (midden) or pit beyond the wall, where it composts for spreading on the fields. Pierces the wall foot.',
    },
    fields: { satisfies: ['waste-drainage'], placement: 'wall' },
    visibility: 'geometry',
    tags: ['drainage', 'midden', 'agriculture', 'waste'],
  },
  {
    id: 'staddle-stones',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['medieval', 'current'] },
    lod: {
      l0: 'Mushroom-shaped stone feet that raise a granary off the ground.',
      l1: ['stone pillar with a flat cap', 'mushroom or toadstool profile', 'a foot under each corner'],
      l2: 'Mushroom-shaped staddle (steddle) stones set under the corners of a timber granary or hayrick, lifting it clear of the damp ground; the broad overhanging caps stop rats and mice from climbing up into the stored grain. They support and present the building above ground.',
    },
    fields: { satisfies: ['vermin-proofing'], placement: 'corner' },
    provenance: ['https://en.wikipedia.org/wiki/Staddle_stones', 'https://en.wikipedia.org/wiki/Granary'],
    visibility: 'geometry',
    tags: ['granary', 'storage', 'stone', 'vermin'],
  },

  // ── TEXTILE WORK ──────────────────────────────────────────────────────────
  {
    id: 'loom',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['ancient', 'classical', 'medieval', 'current'] },
    lod: {
      l0: 'A frame holding warp threads for weaving cloth.',
      l1: ['upright or horizontal timber frame', 'stretched warp threads', 'heddles and treadles', 'a part-woven web'],
      l2: 'A frame on which the warp is held under tension and crossed by the weft to weave cloth. The earlier warp-weighted upright loom gave way in the medieval period to the horizontal treadle loom that let a weaver work faster sitting down. The chief fixture of a weaver\'s house or workshop.',
    },
    fields: { placement: 'centre' },
    visibility: 'data-only',
    tags: ['textile', 'weaving', 'craft', 'workshop'],
  },

  // ── FURNITURE & FIXED INTERIOR JOINERY ────────────────────────────────────
  {
    id: 'settle',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['medieval', 'current'] },
    lod: {
      l0: 'A long high-backed wooden bench, often fixed by the fire.',
      l1: ['tall solid back', 'panelled sides', 'sometimes a chest seat', 'set beside the hearth'],
      l2: 'A heavy wooden bench with a high back and arms (frequently with a hinged box seat for storage), set beside the fire to trap its warmth and screen sitters from draughts. A principal piece of the better hall or tavern.',
    },
    fields: { placement: 'wall' },
    provenance: ['https://en.wikipedia.org/wiki/Settle_(furniture)'],
    visibility: 'data-only',
    tags: ['furniture', 'seating', 'hall', 'comfort'],
  },
  {
    id: 'dais',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['classical', 'medieval'] },
    lod: {
      l0: 'A raised platform at the high end of a hall.',
      l1: ['low timber platform', 'spans the upper end', 'high table upon it', 'often a canopy behind'],
      l2: 'A raised floor at the upper (high) end of a great hall on which the lord\'s high table stands, lifting the household\'s superiors above the common diners on the floor below. Expresses the social order of the hall in built form.',
    },
    fields: { placement: 'centre' },
    visibility: 'data-only',
    tags: ['hall', 'status', 'platform', 'furniture'],
  },
  {
    id: 'trestle-table',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['ancient', 'classical', 'medieval', 'current'] },
    lod: {
      l0: 'A board laid on trestles, dismantled after meals.',
      l1: ['loose plank top', 'pair of A-frame trestles', 'benches alongside'],
      l2: 'A board (or boards) resting on knock-down trestles, set up for a meal and taken apart afterwards to clear the floor of a hall used for many purposes. The ordinary dining furniture before the fixed framed table.',
    },
    fields: { placement: 'centre' },
    visibility: 'data-only',
    tags: ['furniture', 'table', 'hall', 'dining'],
  },

  // ── WATER ─────────────────────────────────────────────────────────────────
  {
    id: 'well',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['ancient', 'classical', 'medieval', 'current'] },
    lod: {
      l0: 'A lined shaft reaching groundwater, with a means to draw it up.',
      l1: ['stone or timber-lined shaft', 'raised parapet wellhead', 'windlass or rope and bucket', 'sometimes a small roof'],
      l2: 'A shaft sunk to the water table and lined to stop it collapsing, topped by a parapet and a windlass, sweep or pulley to raise the bucket. The communal water source of a yard, settlement or monastery; stands free in the open, so it reads fully on the exterior.',
    },
    fields: { satisfies: ['water-supply'], placement: 'centre' },
    provenance: ['https://en.wikipedia.org/wiki/Well'],
    visibility: 'geometry',
    tags: ['water', 'communal', 'shaft'],
  },

  // ── DOVECOTE ──────────────────────────────────────────────────────────────
  {
    id: 'pigeonholes',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['medieval', 'current'], wealth: ['comfortable', 'rich', 'opulent'] },
    lod: {
      l0: 'Tiers of nesting boxes lining a dovecote\'s inner walls.',
      l1: ['rows of small square recesses', 'cover every interior wall', 'L-shaped or alighting ledges'],
      l2: 'The hundreds of nesting cells (nest-holes) built into the inner walls of a dovecote, each housing a breeding pair of pigeons farmed for meat (squabs), eggs and dung. A manorial privilege — the right to keep a dovecote belonged to the lord.',
    },
    fields: { satisfies: ['nesting'], placement: 'wall' },
    provenance: ['https://en.wikipedia.org/wiki/Dovecote'],
    visibility: 'data-only',
    tags: ['dovecote', 'pigeon', 'food', 'manorial'],
  },
  {
    id: 'potence',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['medieval', 'current'] },
    lod: {
      l0: 'A pivoting ladder reaching every nesting box in a dovecote.',
      l1: ['central rotating post', 'arms carrying a ladder', 'swings around the floor', 'sweeps the wall of holes'],
      l2: 'A revolving frame in a dovecote: a central post bearing radial arms and a ladder that pivots around the floor, letting the keeper reach every nesting hole on the walls to collect eggs and squabs and to tend the birds. An ingenious labour-saving fitting of the round or square dovecote.',
    },
    fields: { satisfies: ['nest-access'], placement: 'centre' },
    provenance: ['https://en.wikipedia.org/wiki/Dovecote', 'https://en.wikipedia.org/wiki/Kinwarton_Dovecote'],
    visibility: 'data-only',
    tags: ['dovecote', 'pigeon', 'mechanism', 'access'],
  },

  // ── CHURCH FURNISHINGS ────────────────────────────────────────────────────
  {
    id: 'font',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['classical', 'medieval', 'current'] },
    lod: {
      l0: 'A stone basin near the door for baptism.',
      l1: ['carved stone bowl on a pedestal', 'set near the west door', 'often a heavy lockable cover'],
      l2: 'A carved stone basin, usually placed near the church\'s entrance, holding the water for baptism. Often fitted with a lockable cover to protect the consecrated water. Frequently the oldest surviving fitting in a parish church.',
    },
    fields: { satisfies: ['baptism'], placement: 'corner' },
    provenance: ['https://en.wikipedia.org/wiki/Baptismal_font'],
    visibility: 'data-only',
    tags: ['church', 'worship', 'baptism', 'stone'],
  },
  {
    id: 'altar',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['classical', 'medieval', 'current'] },
    lod: {
      l0: 'The consecrated table at the east end where Mass is offered.',
      l1: ['stone mensa slab', 'five consecration crosses', 'set against the east wall', 'cloth, cross and candles upon it'],
      l2: 'The focus of the church: a consecrated stone table (the mensa, marked with five crosses for the wounds of Christ) at the east end of the chancel where the Eucharist is celebrated. The holiest fixture, toward which the whole building is oriented.',
    },
    fields: { satisfies: ['eucharist'], placement: 'wall' },
    provenance: ['https://en.wikipedia.org/wiki/Altar'],
    visibility: 'data-only',
    tags: ['church', 'worship', 'eucharist', 'stone'],
  },
  {
    id: 'rood-screen',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['medieval'] },
    lod: {
      l0: 'A carved partition dividing nave from chancel, bearing the rood.',
      l1: ['ornate pierced timber screen', 'painted panels below', 'spans the chancel arch', 'great crucifix (rood) above'],
      l2: 'An ornate partition — typically of carved and painted wood — separating the nave (the people\'s part) from the chancel (the clergy\'s part) of a late-medieval church, surmounted by the rood (the great crucifix flanked by Mary and John) on its loft. Marks the boundary of the sacred east end.',
    },
    fields: { satisfies: ['chancel-division'], placement: 'centre' },
    provenance: ['https://en.wikipedia.org/wiki/Rood_screen'],
    visibility: 'data-only',
    tags: ['church', 'worship', 'screen', 'timber'],
  },
  {
    id: 'piscina',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['medieval', 'current'] },
    lod: {
      l0: 'A wall basin draining to holy ground for rinsing sacred vessels.',
      l1: ['shallow stone basin', 'set in a niche by the altar', 'drains through the wall to consecrated ground', 'often a credence shelf'],
      l2: 'A shallow stone basin set in a niche in the chancel wall near the altar, used to rinse the chalice and the priest\'s hands; its drain (sacrarium) carries the water down into consecrated earth rather than the common sewer. A small but near-universal fitting of the medieval chancel.',
    },
    fields: { satisfies: ['sacred-ablution'], placement: 'wall' },
    provenance: ['https://en.wikipedia.org/wiki/Piscina'],
    visibility: 'data-only',
    tags: ['church', 'worship', 'basin', 'stone'],
  },
  {
    id: 'lectern',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['medieval', 'current'] },
    lod: {
      l0: 'A reading stand holding the book for the lessons.',
      l1: ['sloped book-rest on a stem', 'often an eagle with outspread wings', 'brass or carved timber'],
      l2: 'A tall stand with a sloping rest holding the great book from which the scripture lessons are read, commonly carved or cast in the form of an eagle (whose spread wings bear the book). Stands in the chancel or at the chancel step.',
    },
    fields: { satisfies: ['reading'], placement: 'centre' },
    provenance: ['https://en.wikipedia.org/wiki/Lectern'],
    visibility: 'data-only',
    tags: ['church', 'worship', 'furniture', 'reading'],
  },
  {
    id: 'choir-stall',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['medieval', 'current'] },
    lod: {
      l0: 'Fixed canopied seating for the clergy in the chancel.',
      l1: ['rows of carved timber seats', 'high traceried canopies', 'hinged misericord ledges', 'face inward across the choir'],
      l2: 'Fixed rows of richly carved wooden seats lining the sides of the chancel (choir) where the clergy or canons sit for the daily offices; their tip-up seats carry small ledges (misericords) carved underneath to lean on while standing through long services. A major joinery commission.',
    },
    fields: { satisfies: ['clergy-seating'], placement: 'wall' },
    provenance: ['https://en.wikipedia.org/wiki/Choir_(architecture)', 'https://en.wikipedia.org/wiki/Misericord'],
    visibility: 'data-only',
    tags: ['church', 'worship', 'seating', 'timber'],
  },

  // ── LIGHTING ──────────────────────────────────────────────────────────────
  {
    id: 'cresset',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['ancient', 'classical', 'medieval'] },
    lod: {
      l0: 'A stone or iron cup burning oil or fat for light.',
      l1: ['hollowed stone with cups', 'or an iron fire-basket on a pole', 'floating wick in oil', 'smoky flame'],
      l2: 'A vessel for fire used as a light: either a stone hollowed with one or more oil-and-wick cups, or an iron basket of burning pitch or wood raised on a pole or bracket. Lit passages, stairs and courts; the multi-cup cresset stone served places like a monastic dorter.',
    },
    fields: { satisfies: ['lighting'], placement: 'wall' },
    provenance: ['https://en.wikipedia.org/wiki/Cresset'],
    visibility: 'data-only',
    tags: ['lighting', 'fire', 'oil'],
  },
  {
    id: 'rushlight-holder',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['classical', 'medieval', 'current'], wealth: ['destitute', 'poor', 'modest'] },
    lod: {
      l0: 'An iron clip gripping a burning rushlight at an angle.',
      l1: ['sprung iron pincers', 'on a stand or wall bracket', 'a fat-soaked rush smouldering in the jaws'],
      l2: 'A sprung iron clip that grips a rushlight — a peeled rush soaked in kitchen fat — holding it tilted to burn. The cheap light of the poor household, far cheaper than a wax or tallow candle. Often combined with a candle socket for those who could afford the choice.',
    },
    fields: { satisfies: ['lighting'], placement: 'wall' },
    provenance: ['https://en.wikipedia.org/wiki/Rushlight'],
    visibility: 'data-only',
    tags: ['lighting', 'rush', 'poor', 'iron'],
  },

  // ── SITE / YARD GROUND FIXTURES (satisfy establishment requirement tokens) ──
  {
    id: 'hanging-sign',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['medieval', 'current'] },
    lod: {
      l0: 'A painted trade sign hung from a bracket over the door.',
      l1: ['wrought-iron bracket', 'painted board', 'a bush or device for the illiterate'],
      l2: 'A board or carved device projecting on an iron bracket above a tradesman’s door — an ale-stake or bush for a tavern, a device for a craft. Read at a glance by a largely illiterate public; the alehouse’s legal mark of a licensed house.',
    },
    fields: { satisfies: ['signage'], placement: 'wall' },
    provenance: ['https://en.wikipedia.org/wiki/Inn_sign'],
    visibility: 'data-only',
    tags: ['sign', 'frontage', 'trade'],
  },
  {
    id: 'tavern-bench',
    kind: 'fixtureType',
    pack: 'medieval-europe',
    applicability: { eras: ['classical', 'medieval', 'current'] },
    lod: {
      l0: 'A plank bench and board set out in the yard for drinkers.',
      l1: ['trestle board', 'long plank benches', 'set against the sunny wall'],
      l2: 'Rough trestle seating in the tavern yard or against its frontage where customers drink in fine weather — the open-air overflow of the taproom.',
    },
    fields: { satisfies: ['seating'], placement: 'centre' },
    visibility: 'data-only',
    tags: ['seating', 'yard', 'timber'],
  },
];
