/**
 * GENERATED by `npx tsx scripts/motion-import-bvh.ts dig` — do not
 * hand-edit; re-run to change. Byte-identity is pinned by
 * `tests/unit/motion-import-determinism.test.ts`.
 *
 * Capture: vendor/mocap/cmu/79_04.bvh — CMU Graphics Lab Motion Capture
 * Database, cgspeed BVH conversion, 120 fps (see CREDITS.md).
 *
 * digging, in place. No footfall cycle to find here — the stance foot never
 * leaves the ground for the whole capture (`--contacts` shows LeftFoot in
 * stance 1-909), so the cycle comes from the swing of the dig itself:
 * `--periods --from 540` finds P=148 minimizes the first/last pose distance
 * (0.756px) at 0.4px of travel, which is the in-place confirmation
 * `--contacts` cannot give. Range [540, 688]. `--sweep` shows the SAME
 * two-knob story the wave was imported under, independently reproduced: at the
 * default 12 keys, MORE frames makes the fit WORSE, not better (33 frames:
 * 4.1deg RMS; 65 frames: 4.9deg RMS) because 65 baked poses are being asked to
 * fit through the same 12-key budget that 33 already strained. Frames alone
 * cannot fix that — 33 frames plateaus at 2.9deg RMS / 18.8deg peak past
 * maxKeys 20, no matter how high maxKeys goes. Raising BOTH — frames to 65,
 * maxKeys to 24 — reaches 1.6deg RMS / 6.3deg peak, better than the walk at 9
 * frames (5.6 / 19.4) and the wave at 33/24 (4.8 / 13.8). Frontal forearms
 * ride `mode: 'translate'` here too: this capture is the ±107deg flail case
 * the bone-map fix exists for, and profile (`left`) keeps its rotation
 * (0.61-0.95 in-plane across the dig, against 0.22-0.34 frontal). HONEST
 * ASTERISK: `left` does not loop-close (`loop: 'auto'` measures an 11.5deg gap
 * on `armFar_up`, over the 8deg tolerance) while `down`/`up` close at 0deg — a
 * real shoulder-angle mismatch between this range's endpoints, not a fitting
 * artifact (constant across maxKeys 24..48, and shifting the start frame ±5
 * only gets it to 10.5deg). So `IMPORTED_CLIP_META.loop` reads false for the
 * whole clip even though the capture visibly repeats; the west view is the one
 * that will show a small pop at the wrap. Left for the studio (M2) to judge
 * against the render, not smoothed over here.
 *
 * Options: range [540, 688] · frames 65 ·
 *   referenceFrame 'mean' ·
 *   loop 'auto' · rootMotion 'in-place' (default) ·
 *   pxPerUnit 1.903233 (51 px figure ÷ T-pose extent 26.797 units)
 *
 * Cycle: 148 source frames = 1.2333 s.
 * Stride: 0.4 px per cycle — under the 1 px floor, so this is capture
 *   noise rather than travel. Recorded as stride 0 / ground speed 0, which is
 *   the honest reading: play it on an NPC standing still.
 * Loop residual (capture, first→last pose): 0.76 px RMS per joint.
 *
 * Sampling: 2.31 source frames between baked samples (19.3 ms per frame).
 *   DECIMATION ERROR vs an undecimated bake of the same range: 1.6° RMS,
 *   6.3° peak, worst on armR_up (up).
 *   That is the whole aliasing question answered by measurement: an under-sampled
 *   wiggle reconstructs to the wrong shape and this number blows up. Re-run the
 *   importer to check it rather than trusting this sentence.
 *
 * Per facing — tracks, worst per-frame angle step, t=0..t=1 gap, plants,
 * and the foreshortening floor (least of any rotating bone in-plane length):
 *   down  10 tracks · max    107° · step  34.5° (armL_up) · loop 0° · 1 plant(s) · in-plane ≥ 0.11 (armR_up)
 *   up    10 tracks · max    107° · step  34.5° (armR_up) · loop 0° · 1 plant(s) · in-plane ≥ 0.11 (armL_up)
 *   left  10 tracks · max     73° · step    33° (armNear_fore) · loop 11.5° · 1 plant(s) · in-plane ≥ 0.52 (armNear_fore)
 *
 * A per-frame step approaching 180° would mean the gesture outran the baked
 * rate and the angle unwrapper picked the wrong branch. A foreshortening
 * floor approaching 0 would mean a bone points at the camera and the rig is
 * rotating a chip on noise. Neither happens here — the captures that DID
 * fail those two reads are listed, with their numbers, in the importer.
 */

import type { Clip } from '../rig';
import type { ImportedClipMeta } from '../clip-meta';

/** Capture facts a player can feel: cadence, travel, and whether it loops. */
export const CLIP_DIG_META: ImportedClipMeta = {
  source: '79_04.bvh',
  cycleSeconds: 1.2333,
  frameMs: 19.3,
  stridePx: 0,
  groundSpeedPxPerSec: 0,
  loop: false,
};

export const CLIP_DIG_DOWN: Clip = {
  name: 'dig',
  frames: 65,
  tracks: {
    trunk: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 1, deg: 0, dx: 0, dy: 0 },
    ],
    head: [
      { t: 0, deg: 0, dx: -1.75, dy: -2.5 },
      { t: 0.15625, deg: 0, dx: 1.25, dy: -1.75 },
      { t: 0.234375, deg: 0, dx: 2.5, dy: 1.25 },
      { t: 0.296875, deg: 0, dx: 2, dy: 2.25 },
      { t: 0.546875, deg: 0, dx: 1.25, dy: 2.5 },
      { t: 0.578125, deg: 0, dx: 0.25, dy: 1.75 },
      { t: 0.703125, deg: 0, dx: -2.75, dy: -1.25 },
      { t: 1, deg: 0, dx: -1.75, dy: -2.5 },
    ],
    armL_up: [
      { t: 0, deg: -22.5, dx: -1.75, dy: -2.25 },
      { t: 0.046875, deg: -9, dx: -1, dy: -2.75 },
      { t: 0.0625, deg: -1, dx: -0.75, dy: -3 },
      { t: 0.078125, deg: 13, dx: -0.25, dy: -3 },
      { t: 0.109375, deg: 49, dx: 0.25, dy: -3 },
      { t: 0.125, deg: 75, dx: 0.5, dy: -3 },
      { t: 0.140625, deg: 88.5, dx: 0.75, dy: -3 },
      { t: 0.15625, deg: 98.5, dx: 1, dy: -2.75 },
      { t: 0.1875, deg: 107, dx: 1.75, dy: -2.5 },
      { t: 0.203125, deg: 102.5, dx: 2, dy: -2.25 },
      { t: 0.21875, deg: 90.5, dx: 2.25, dy: -1.5 },
      { t: 0.234375, deg: 56, dx: 2.5, dy: -0.5 },
      { t: 0.25, deg: 33.5, dx: 2.5, dy: 0.25 },
      { t: 0.265625, deg: 16.5, dx: 2.5, dy: 1 },
      { t: 0.28125, deg: 10.5, dx: 2.25, dy: 2 },
      { t: 0.375, deg: 22.5, dx: 2.25, dy: 2 },
      { t: 0.453125, deg: 23, dx: 2.25, dy: 2 },
      { t: 0.515625, deg: -8.5, dx: 1.25, dy: 2.75 },
      { t: 0.53125, deg: -17, dx: 1, dy: 2.75 },
      { t: 0.578125, deg: -28.5, dx: 0, dy: 2.75 },
      { t: 0.6875, deg: -42, dx: -2, dy: 1 },
      { t: 0.78125, deg: -39.5, dx: -2.5, dy: -1 },
      { t: 0.90625, deg: -35, dx: -2.75, dy: -1.25 },
      { t: 1, deg: -22.5, dx: -1.75, dy: -2.25 },
    ],
    armL_fore: [
      { t: 0, deg: 22.5, dx: -1.5, dy: -2.25 },
      { t: 0.046875, deg: 9, dx: -0.5, dy: -3 },
      { t: 0.0625, deg: 1, dx: -0.25, dy: -2.75 },
      { t: 0.078125, deg: -13, dx: 0.5, dy: -2.25 },
      { t: 0.109375, deg: -49, dx: 3, dy: 0 },
      { t: 0.125, deg: -75, dx: 3, dy: 0.5 },
      { t: 0.140625, deg: -88.5, dx: 3, dy: 0.5 },
      { t: 0.15625, deg: -98.5, dx: 3, dy: 0.5 },
      { t: 0.1875, deg: -107, dx: 3, dy: 0.5 },
      { t: 0.203125, deg: -102.5, dx: 3, dy: 0.75 },
      { t: 0.21875, deg: -90.5, dx: 2.75, dy: 1.25 },
      { t: 0.234375, deg: -56, dx: 1.75, dy: 2.5 },
      { t: 0.25, deg: -33.5, dx: 0.25, dy: 3 },
      { t: 0.265625, deg: -16.5, dx: -1, dy: 2.75 },
      { t: 0.28125, deg: -10.5, dx: -1.5, dy: 2.5 },
      { t: 0.375, deg: -22.5, dx: 0.5, dy: 3 },
      { t: 0.453125, deg: -23, dx: 0.5, dy: 2.75 },
      { t: 0.515625, deg: 8.5, dx: -1.25, dy: -0.25 },
      { t: 0.53125, deg: 17, dx: -1.75, dy: -1 },
      { t: 0.578125, deg: 28.5, dx: -1.75, dy: -2.25 },
      { t: 0.6875, deg: 42, dx: -2.25, dy: -1.75 },
      { t: 0.828125, deg: 40.5, dx: -1.75, dy: -2.75 },
      { t: 0.90625, deg: 35, dx: -2.25, dy: -1.75 },
      { t: 1, deg: 22.5, dx: -1.5, dy: -2.25 },
    ],
    armR_up: [
      { t: 0, deg: 0.5, dx: -1.25, dy: -2.75 },
      { t: 0.109375, deg: 8.5, dx: 0.25, dy: -1 },
      { t: 0.140625, deg: 14.5, dx: 1, dy: 0 },
      { t: 0.1875, deg: 25.5, dx: 1.5, dy: 2 },
      { t: 0.234375, deg: 29, dx: 1.5, dy: 2.75 },
      { t: 0.296875, deg: 13, dx: 1.25, dy: 2.75 },
      { t: 0.40625, deg: 15.5, dx: 1, dy: 2.75 },
      { t: 0.46875, deg: 13.5, dx: 1, dy: 2.75 },
      { t: 0.5625, deg: -2.5, dx: 1, dy: 2.75 },
      { t: 0.578125, deg: -6, dx: 0.75, dy: 2 },
      { t: 0.671875, deg: -20, dx: -1.5, dy: -2.5 },
      { t: 0.703125, deg: -26.5, dx: -1.25, dy: -2.75 },
      { t: 0.734375, deg: -32, dx: -1.25, dy: -2.75 },
      { t: 0.78125, deg: -35.5, dx: -1.25, dy: -2.75 },
      { t: 0.828125, deg: -33.5, dx: -1.25, dy: -2.75 },
      { t: 0.84375, deg: -3, dx: -1.25, dy: -2.75 },
      { t: 0.875, deg: -11, dx: -1.25, dy: -2.75 },
      { t: 1, deg: 0.5, dx: -1.25, dy: -2.75 },
    ],
    armR_fore: [
      { t: 0, deg: -0.5, dx: 0, dy: 1 },
      { t: 0.03125, deg: -1.5, dx: 0.5, dy: 1.75 },
      { t: 0.109375, deg: -8.5, dx: 0.5, dy: 0.5 },
      { t: 0.203125, deg: -27.5, dx: -0.25, dy: -2.25 },
      { t: 0.234375, deg: -29, dx: 0.75, dy: -0.5 },
      { t: 0.296875, deg: -13, dx: 1.75, dy: 2.5 },
      { t: 0.421875, deg: -15.5, dx: 1.75, dy: 2.5 },
      { t: 0.5, deg: -9.5, dx: 1.5, dy: 2.75 },
      { t: 0.53125, deg: -3, dx: 1, dy: 2.75 },
      { t: 0.640625, deg: 15.5, dx: 0.25, dy: 2.75 },
      { t: 0.671875, deg: 20, dx: 0.25, dy: 2.5 },
      { t: 0.6875, deg: 24, dx: 0, dy: 1.25 },
      { t: 0.734375, deg: 32, dx: 0.25, dy: -2 },
      { t: 0.75, deg: 33.5, dx: 0.25, dy: -3 },
      { t: 0.78125, deg: 35.5, dx: 0.25, dy: -3 },
      { t: 0.828125, deg: 33.5, dx: 0, dy: -3 },
      { t: 0.84375, deg: 3, dx: -0.25, dy: -3 },
      { t: 0.875, deg: 11, dx: 0, dy: -3 },
      { t: 0.921875, deg: 6.5, dx: -0.25, dy: -3 },
      { t: 0.9375, deg: 4, dx: -0.5, dy: -2.25 },
      { t: 1, deg: -0.5, dx: 0, dy: 1 },
    ],
    legL_up: [
      { t: 0, deg: -3.5, dx: 0, dy: 0 },
      { t: 0.109375, deg: -2, dx: 0, dy: 0 },
      { t: 0.1875, deg: 3, dx: -0.25, dy: -0.25 },
      { t: 0.40625, deg: 5.5, dx: -0.25, dy: 0 },
      { t: 0.71875, deg: -3, dx: 0.25, dy: 0.25 },
      { t: 1, deg: -3.5, dx: 0, dy: 0 },
    ],
    legL_fore: [
      { t: 0, deg: 0, dx: 0.5, dy: 0.5 },
      { t: 0.21875, deg: 0, dx: -0.75, dy: 0 },
      { t: 0.296875, deg: 0, dx: -0.5, dy: -0.75 },
      { t: 1, deg: 0, dx: 0.5, dy: 0.5 },
    ],
    legR_up: [
      { t: 0, deg: 1, dx: 0, dy: -0.25 },
      { t: 1, deg: 1, dx: 0, dy: -0.25 },
    ],
    legR_fore: [
      { t: 0, deg: -1, dx: 0, dy: 0.25 },
      { t: 0.140625, deg: -3, dx: 0, dy: 0.25 },
      { t: 0.234375, deg: 0, dx: 0, dy: 0 },
      { t: 0.640625, deg: 2, dx: 0, dy: 0 },
      { t: 1, deg: -1, dx: 0, dy: 0.25 },
    ],
  },
  plant: [
    { chip: 'legR_fore', point: [39.5, 62] },
  ],
};

export const CLIP_DIG_UP: Clip = {
  name: 'dig',
  frames: 65,
  tracks: {
    trunk: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 1, deg: 0, dx: 0, dy: 0 },
    ],
    head: [
      { t: 0, deg: 0, dx: 1.75, dy: -2.5 },
      { t: 0.15625, deg: 0, dx: -1.25, dy: -1.75 },
      { t: 0.234375, deg: 0, dx: -2.5, dy: 1.25 },
      { t: 0.296875, deg: 0, dx: -2, dy: 2.25 },
      { t: 0.546875, deg: 0, dx: -1.25, dy: 2.5 },
      { t: 0.578125, deg: 0, dx: -0.25, dy: 1.75 },
      { t: 0.703125, deg: 0, dx: 2.75, dy: -1.25 },
      { t: 1, deg: 0, dx: 1.75, dy: -2.5 },
    ],
    armL_up: [
      { t: 0, deg: -0.5, dx: 1.25, dy: -2.75 },
      { t: 0.109375, deg: -8.5, dx: -0.25, dy: -1 },
      { t: 0.140625, deg: -14.5, dx: -1, dy: 0 },
      { t: 0.1875, deg: -25.5, dx: -1.5, dy: 2 },
      { t: 0.234375, deg: -29, dx: -1.5, dy: 2.75 },
      { t: 0.296875, deg: -13, dx: -1.25, dy: 2.75 },
      { t: 0.40625, deg: -15.5, dx: -1, dy: 2.75 },
      { t: 0.46875, deg: -13.5, dx: -1, dy: 2.75 },
      { t: 0.5625, deg: 2.5, dx: -1, dy: 2.75 },
      { t: 0.578125, deg: 6, dx: -0.75, dy: 2 },
      { t: 0.671875, deg: 20, dx: 1.5, dy: -2.5 },
      { t: 0.703125, deg: 26.5, dx: 1.25, dy: -2.75 },
      { t: 0.734375, deg: 32, dx: 1.25, dy: -2.75 },
      { t: 0.78125, deg: 35.5, dx: 1.25, dy: -2.75 },
      { t: 0.828125, deg: 33.5, dx: 1.25, dy: -2.75 },
      { t: 0.84375, deg: 3, dx: 1.25, dy: -2.75 },
      { t: 0.875, deg: 11, dx: 1.25, dy: -2.75 },
      { t: 1, deg: -0.5, dx: 1.25, dy: -2.75 },
    ],
    armL_fore: [
      { t: 0, deg: 0.5, dx: 0, dy: 1 },
      { t: 0.046875, deg: 2.5, dx: -0.5, dy: 1.5 },
      { t: 0.109375, deg: 8.5, dx: -0.25, dy: 0 },
      { t: 0.171875, deg: 21, dx: 0, dy: -2.25 },
      { t: 0.1875, deg: 25.5, dx: 0.25, dy: -2.75 },
      { t: 0.21875, deg: 29, dx: 0, dy: -2.75 },
      { t: 0.234375, deg: 29, dx: -0.5, dy: -1.5 },
      { t: 0.296875, deg: 13, dx: -1.75, dy: 2.25 },
      { t: 0.421875, deg: 15.5, dx: -1.75, dy: 2.25 },
      { t: 0.5, deg: 9.5, dx: -1.5, dy: 2.5 },
      { t: 0.546875, deg: 0, dx: -0.75, dy: 2.75 },
      { t: 0.578125, deg: -6, dx: -0.5, dy: 2.75 },
      { t: 0.671875, deg: -20, dx: 0, dy: 3 },
      { t: 0.703125, deg: -26.5, dx: 0.25, dy: 1 },
      { t: 0.734375, deg: -32, dx: 0.25, dy: -1 },
      { t: 0.78125, deg: -35.5, dx: 0, dy: -3 },
      { t: 0.828125, deg: -33.5, dx: 0.25, dy: -3 },
      { t: 0.84375, deg: -3, dx: 0.25, dy: -3 },
      { t: 0.875, deg: -11, dx: 0, dy: -3 },
      { t: 0.921875, deg: -6.5, dx: 0.25, dy: -3 },
      { t: 0.9375, deg: -4, dx: 0.5, dy: -2 },
      { t: 1, deg: 0.5, dx: 0, dy: 1 },
    ],
    armR_up: [
      { t: 0, deg: 22.5, dx: 1.75, dy: -2.25 },
      { t: 0.046875, deg: 9, dx: 1, dy: -2.75 },
      { t: 0.0625, deg: 1, dx: 0.75, dy: -3 },
      { t: 0.078125, deg: -13, dx: 0.25, dy: -3 },
      { t: 0.109375, deg: -49, dx: -0.25, dy: -3 },
      { t: 0.125, deg: -75, dx: -0.5, dy: -3 },
      { t: 0.140625, deg: -88.5, dx: -0.75, dy: -3 },
      { t: 0.15625, deg: -98.5, dx: -1, dy: -2.75 },
      { t: 0.1875, deg: -107, dx: -1.75, dy: -2.5 },
      { t: 0.203125, deg: -102.5, dx: -2, dy: -2.25 },
      { t: 0.21875, deg: -90.5, dx: -2.25, dy: -1.5 },
      { t: 0.234375, deg: -56, dx: -2.5, dy: -0.5 },
      { t: 0.25, deg: -33.5, dx: -2.5, dy: 0.25 },
      { t: 0.265625, deg: -16.5, dx: -2.5, dy: 1 },
      { t: 0.28125, deg: -10.5, dx: -2.25, dy: 2 },
      { t: 0.375, deg: -22.5, dx: -2.25, dy: 2 },
      { t: 0.453125, deg: -23, dx: -2.25, dy: 2 },
      { t: 0.515625, deg: 8.5, dx: -1.25, dy: 2.75 },
      { t: 0.53125, deg: 17, dx: -1, dy: 2.75 },
      { t: 0.578125, deg: 28.5, dx: 0, dy: 2.75 },
      { t: 0.6875, deg: 42, dx: 2, dy: 1 },
      { t: 0.78125, deg: 39.5, dx: 2.5, dy: -1 },
      { t: 0.90625, deg: 35, dx: 2.75, dy: -1.25 },
      { t: 1, deg: 22.5, dx: 1.75, dy: -2.25 },
    ],
    armR_fore: [
      { t: 0, deg: -22.5, dx: 1.75, dy: -1.5 },
      { t: 0.046875, deg: -9, dx: 0.75, dy: -2.75 },
      { t: 0.0625, deg: -1, dx: 0.25, dy: -2.75 },
      { t: 0.078125, deg: 13, dx: -0.5, dy: -2.75 },
      { t: 0.109375, deg: 49, dx: -2.5, dy: -1.5 },
      { t: 0.125, deg: 75, dx: -3, dy: -0.75 },
      { t: 0.140625, deg: 88.5, dx: -3, dy: -0.5 },
      { t: 0.15625, deg: 98.5, dx: -3, dy: -0.5 },
      { t: 0.1875, deg: 107, dx: -3, dy: 0 },
      { t: 0.203125, deg: 102.5, dx: -3, dy: 0.25 },
      { t: 0.21875, deg: 90.5, dx: -3, dy: 0.75 },
      { t: 0.234375, deg: 56, dx: -2, dy: 2.25 },
      { t: 0.25, deg: 33.5, dx: 0, dy: 2.75 },
      { t: 0.265625, deg: 16.5, dx: 1.25, dy: 2.75 },
      { t: 0.28125, deg: 10.5, dx: 1.5, dy: 2.25 },
      { t: 0.375, deg: 22.5, dx: -0.25, dy: 2.75 },
      { t: 0.453125, deg: 23, dx: -0.25, dy: 2 },
      { t: 0.515625, deg: -8.5, dx: 1.5, dy: 0 },
      { t: 0.53125, deg: -17, dx: 1.75, dy: -0.5 },
      { t: 0.578125, deg: -28.5, dx: 2, dy: -1.25 },
      { t: 0.6875, deg: -42, dx: 2.75, dy: -0.5 },
      { t: 0.828125, deg: -40.5, dx: 2.25, dy: -1.5 },
      { t: 0.90625, deg: -35, dx: 2.5, dy: -0.5 },
      { t: 1, deg: -22.5, dx: 1.75, dy: -1.5 },
    ],
    legL_up: [
      { t: 0, deg: -1, dx: 0, dy: -0.25 },
      { t: 1, deg: -1, dx: 0, dy: -0.25 },
    ],
    legL_fore: [
      { t: 0, deg: 1, dx: 0, dy: 0.25 },
      { t: 0.140625, deg: 3, dx: 0, dy: 0.25 },
      { t: 0.234375, deg: 0, dx: 0, dy: 0 },
      { t: 0.640625, deg: -2, dx: 0, dy: 0 },
      { t: 1, deg: 1, dx: 0, dy: 0.25 },
    ],
    legR_up: [
      { t: 0, deg: 3.5, dx: 0, dy: 0 },
      { t: 0.109375, deg: 2, dx: 0, dy: 0 },
      { t: 0.1875, deg: -3, dx: 0.25, dy: -0.25 },
      { t: 0.40625, deg: -5.5, dx: 0.25, dy: 0 },
      { t: 0.71875, deg: 3, dx: -0.25, dy: 0.25 },
      { t: 1, deg: 3.5, dx: 0, dy: 0 },
    ],
    legR_fore: [
      { t: 0, deg: 0, dx: -0.5, dy: 0.5 },
      { t: 0.21875, deg: 0, dx: 0.75, dy: 0 },
      { t: 0.296875, deg: 0, dx: 0.5, dy: -0.75 },
      { t: 1, deg: 0, dx: -0.5, dy: 0.5 },
    ],
  },
  plant: [
    { chip: 'legL_fore', point: [24.5, 62] },
  ],
};

export const CLIP_DIG_LEFT: Clip = {
  name: 'dig',
  frames: 65,
  tracks: {
    trunk: [
      { t: 0, deg: 0, dx: -1.75, dy: 0 },
      { t: 0.171875, deg: 0, dx: -0.5, dy: 0 },
      { t: 0.28125, deg: 0, dx: 2, dy: 0 },
      { t: 0.515625, deg: 0, dx: 2.25, dy: 0 },
      { t: 0.609375, deg: 0, dx: 1.75, dy: 0 },
      { t: 0.671875, deg: 0, dx: 1, dy: 0 },
      { t: 0.734375, deg: 0, dx: -1, dy: 0 },
      { t: 0.828125, deg: 0, dx: -3, dy: 0.25 },
      { t: 1, deg: 0, dx: -1.25, dy: 0.25 },
    ],
    head: [
      { t: 0, deg: 3.5, dx: 2.25, dy: -2 },
      { t: 0.03125, deg: -2, dx: 2, dy: -2.25 },
      { t: 0.15625, deg: -14.5, dx: 0, dy: -1.75 },
      { t: 0.1875, deg: -18, dx: -1.25, dy: -0.75 },
      { t: 0.25, deg: -23, dx: -2.75, dy: 1.5 },
      { t: 0.359375, deg: -27, dx: -2.25, dy: 2 },
      { t: 0.46875, deg: -22, dx: -2.25, dy: 2 },
      { t: 0.5625, deg: -10.5, dx: -2.5, dy: 1.5 },
      { t: 0.609375, deg: -0.5, dx: -2.75, dy: 1 },
      { t: 0.625, deg: 4.5, dx: -2.25, dy: 0.5 },
      { t: 0.671875, deg: 15, dx: -0.75, dy: -0.5 },
      { t: 0.6875, deg: 19.5, dx: 0.25, dy: -1 },
      { t: 0.734375, deg: 29.5, dx: 2.5, dy: -1.75 },
      { t: 0.8125, deg: 41.5, dx: 2.75, dy: -1.25 },
      { t: 0.890625, deg: 34, dx: 2.75, dy: -1.25 },
      { t: 0.921875, deg: 28, dx: 2.75, dy: -1.25 },
      { t: 0.9375, deg: 23, dx: 2.75, dy: -1.5 },
      { t: 1, deg: 7, dx: 2.25, dy: -2 },
    ],
    armNear_up: [
      { t: 0, deg: -11.5, dx: 0.5, dy: -3 },
      { t: 0.046875, deg: -24.5, dx: 0, dy: -2.5 },
      { t: 0.078125, deg: -31.5, dx: -0.25, dy: -1.75 },
      { t: 0.171875, deg: -48.5, dx: -0.75, dy: 1 },
      { t: 0.203125, deg: -51.5, dx: -1.25, dy: 2.5 },
      { t: 0.21875, deg: -50, dx: -1.25, dy: 2.75 },
      { t: 0.234375, deg: -37, dx: -1.25, dy: 2.75 },
      { t: 0.265625, deg: -7, dx: -1, dy: 2.75 },
      { t: 0.296875, deg: -16, dx: -1, dy: 2.75 },
      { t: 0.421875, deg: -14, dx: -0.75, dy: 3 },
      { t: 0.484375, deg: -18.5, dx: -1, dy: 2.75 },
      { t: 0.5625, deg: -12, dx: -2, dy: 2.25 },
      { t: 0.609375, deg: -3, dx: -3, dy: 0.75 },
      { t: 0.640625, deg: 7, dx: -2.5, dy: -1.25 },
      { t: 0.671875, deg: 18, dx: -1.5, dy: -2.5 },
      { t: 0.703125, deg: 33, dx: 0, dy: -3 },
      { t: 0.734375, deg: 47.5, dx: 1.25, dy: -2.75 },
      { t: 0.75, deg: 53, dx: 1.5, dy: -2.75 },
      { t: 0.8125, deg: 69.5, dx: 2, dy: -2.25 },
      { t: 0.859375, deg: 61, dx: 2, dy: -2.25 },
      { t: 0.890625, deg: 48, dx: 2, dy: -2.25 },
      { t: 0.921875, deg: 34.5, dx: 1.75, dy: -2.5 },
      { t: 0.9375, deg: 23.5, dx: 1.5, dy: -2.5 },
      { t: 1, deg: -10, dx: 0.75, dy: -3 },
    ],
    armNear_fore: [
      { t: 0, deg: 21, dx: -0.25, dy: 1.5 },
      { t: 0.0625, deg: 28.5, dx: -0.75, dy: 2.75 },
      { t: 0.078125, deg: 35.5, dx: -0.75, dy: 3 },
      { t: 0.125, deg: 49, dx: -1, dy: 2.75 },
      { t: 0.171875, deg: 52, dx: -1, dy: 2.75 },
      { t: 0.203125, deg: 45.5, dx: -1.25, dy: 2.75 },
      { t: 0.21875, deg: 37.5, dx: -1.5, dy: 2.75 },
      { t: 0.234375, deg: 7, dx: -1.5, dy: 2.5 },
      { t: 0.25, deg: -26, dx: -1.5, dy: 2.75 },
      { t: 0.265625, deg: -52.5, dx: -1.25, dy: 2.75 },
      { t: 0.296875, deg: -39, dx: -1.25, dy: 2.75 },
      { t: 0.4375, deg: -40.5, dx: -1.25, dy: 2.75 },
      { t: 0.484375, deg: -30, dx: -1.5, dy: 2.75 },
      { t: 0.5625, deg: -21.5, dx: -1.5, dy: 2.5 },
      { t: 0.671875, deg: -14.5, dx: -0.75, dy: 0.5 },
      { t: 0.71875, deg: -11, dx: -2, dy: -2 },
      { t: 0.75, deg: -2, dx: -2, dy: -2.25 },
      { t: 0.765625, deg: 5, dx: -2, dy: -2.25 },
      { t: 0.78125, deg: 27.5, dx: -2, dy: -2.25 },
      { t: 0.796875, deg: 46.5, dx: -2, dy: -2.25 },
      { t: 0.8125, deg: 56.5, dx: -2, dy: -2.25 },
      { t: 0.875, deg: 15.5, dx: -1.5, dy: -2.5 },
      { t: 0.9375, deg: 10, dx: -0.5, dy: -2.5 },
      { t: 1, deg: 9.5, dx: -0.25, dy: 1.5 },
    ],
    armFar_up: [
      { t: 0, deg: -11.5, dx: 2.75, dy: -1.5 },
      { t: 0.046875, deg: -29.5, dx: 2.25, dy: -2 },
      { t: 0.078125, deg: -40.5, dx: 2, dy: -2.25 },
      { t: 0.171875, deg: -69.5, dx: 0.25, dy: -3 },
      { t: 0.203125, deg: -73, dx: -1.75, dy: -2.25 },
      { t: 0.21875, deg: -68.5, dx: -2.5, dy: -1.5 },
      { t: 0.234375, deg: -45, dx: -3, dy: -0.25 },
      { t: 0.25, deg: -19, dx: -3, dy: 0.25 },
      { t: 0.265625, deg: 0, dx: -3, dy: 0.5 },
      { t: 0.296875, deg: 0, dx: -2.75, dy: 1.5 },
      { t: 0.4375, deg: -19, dx: -2.75, dy: 1.25 },
      { t: 0.59375, deg: -1, dx: -2.25, dy: 2 },
      { t: 0.65625, deg: 17.5, dx: -1, dy: 1.5 },
      { t: 0.671875, deg: 24, dx: -0.75, dy: 1.25 },
      { t: 0.6875, deg: 33, dx: 0, dy: 1 },
      { t: 0.71875, deg: 45, dx: 1.25, dy: 0.25 },
      { t: 0.734375, deg: 53, dx: 2, dy: 0 },
      { t: 0.75, deg: 57.5, dx: 2.5, dy: -0.5 },
      { t: 0.796875, deg: 64.5, dx: 3, dy: -0.75 },
      { t: 0.859375, deg: 59.5, dx: 3, dy: -0.5 },
      { t: 0.875, deg: 53.5, dx: 3, dy: -0.5 },
      { t: 0.921875, deg: 37, dx: 3, dy: -0.75 },
      { t: 0.9375, deg: 28.5, dx: 3, dy: -0.75 },
      { t: 1, deg: -1, dx: 2.75, dy: -1.5 },
    ],
    armFar_fore: [
      { t: 0, deg: 15, dx: 3, dy: 0.25 },
      { t: 0.046875, deg: 16, dx: 2.5, dy: -0.75 },
      { t: 0.078125, deg: 20.5, dx: 2.5, dy: -1.5 },
      { t: 0.125, deg: 28.5, dx: 2, dy: -2.25 },
      { t: 0.203125, deg: 34.5, dx: 1.25, dy: -2.75 },
      { t: 0.21875, deg: 30.5, dx: 1, dy: -2.75 },
      { t: 0.234375, deg: 8, dx: -0.25, dy: -3 },
      { t: 0.25, deg: -20.5, dx: -1, dy: -1.5 },
      { t: 0.265625, deg: -41, dx: -0.75, dy: 0.75 },
      { t: 0.28125, deg: -40, dx: -1, dy: 1.75 },
      { t: 0.3125, deg: -40.5, dx: -1.75, dy: 1.75 },
      { t: 0.4375, deg: -32.5, dx: -2.5, dy: -0.5 },
      { t: 0.515625, deg: -23, dx: -1.25, dy: 1.75 },
      { t: 0.53125, deg: -19.5, dx: -1, dy: 2.25 },
      { t: 0.625, deg: -7, dx: 1.5, dy: 2 },
      { t: 0.71875, deg: 2.5, dx: 2.25, dy: 2 },
      { t: 0.765625, deg: 13.5, dx: 2.5, dy: 1.75 },
      { t: 0.78125, deg: 25.5, dx: 2.5, dy: 1.5 },
      { t: 0.796875, deg: 34, dx: 2.75, dy: 1.5 },
      { t: 0.8125, deg: 38, dx: 2.75, dy: 1.25 },
      { t: 0.828125, deg: 30, dx: 3, dy: 0.75 },
      { t: 0.859375, deg: 23, dx: 3, dy: 0.5 },
      { t: 1, deg: 7, dx: 3, dy: 0.25 },
    ],
    legNear_up: [
      { t: 0, deg: -7, dx: -0.75, dy: -0.25 },
      { t: 0.109375, deg: -7, dx: -0.75, dy: 0 },
      { t: 0.15625, deg: -4, dx: -0.75, dy: 0 },
      { t: 0.203125, deg: 1, dx: -0.25, dy: 0.25 },
      { t: 0.296875, deg: 8.5, dx: 0.75, dy: 0.25 },
      { t: 0.609375, deg: 6.5, dx: 0.5, dy: 0 },
      { t: 0.78125, deg: -7, dx: -0.25, dy: -0.25 },
      { t: 0.875, deg: -9.5, dx: -0.75, dy: -0.25 },
      { t: 1, deg: -7, dx: -1, dy: -0.25 },
    ],
    legNear_fore: [
      { t: 0, deg: 4.5, dx: 1.25, dy: 0.5 },
      { t: 0.109375, deg: 4.5, dx: 1, dy: 0.5 },
      { t: 0.15625, deg: 1.5, dx: 0.75, dy: 0.25 },
      { t: 0.203125, deg: -2.5, dx: -0.25, dy: 0 },
      { t: 0.296875, deg: -6, dx: -1.5, dy: 0 },
      { t: 0.609375, deg: -3.5, dx: -1.25, dy: 0 },
      { t: 0.78125, deg: 5, dx: 1.25, dy: 0.5 },
      { t: 1, deg: 5, dx: 1.25, dy: 0.5 },
    ],
    legFar_up: [
      { t: 0, deg: 5, dx: -0.25, dy: 0 },
      { t: 0.171875, deg: 5, dx: -0.25, dy: -0.25 },
      { t: 0.265625, deg: -7, dx: 0.5, dy: 0 },
      { t: 0.296875, deg: -12, dx: 0.75, dy: 0 },
      { t: 0.515625, deg: -9, dx: 0.5, dy: 0 },
      { t: 0.625, deg: -5, dx: 0.25, dy: 0.25 },
      { t: 0.78125, deg: 9.5, dx: -0.75, dy: 0 },
      { t: 1, deg: 6.5, dx: -0.25, dy: 0 },
    ],
    legFar_fore: [
      { t: 0, deg: 0, dx: -0.75, dy: 0.5 },
      { t: 0.171875, deg: 0, dx: -0.75, dy: 0 },
      { t: 0.296875, deg: 0, dx: 2, dy: 0 },
      { t: 0.625, deg: 0, dx: 0.75, dy: 0.25 },
      { t: 0.78125, deg: 0, dx: -1.5, dy: 0.5 },
      { t: 1, deg: 0, dx: -1, dy: 0.5 },
    ],
  },
  plant: [
    { chip: 'legNear_fore', point: [27.5, 60] },
  ],
};

/** The three AUTHORED facings; east is west mirrored at bake time (`facing.ts`). */
export const CLIP_DIG: Readonly<Record<'down' | 'up' | 'left', Clip>> = {
  down: CLIP_DIG_DOWN,
  up: CLIP_DIG_UP,
  left: CLIP_DIG_LEFT,
};
