/**
 * GENERATED by `npx tsx scripts/motion-import-bvh.ts` — do not hand-edit;
 * re-run to change. Byte-identity is pinned by
 * `tests/unit/motion-import-determinism.test.ts`.
 *
 * Every clip imported from the vendored CMU captures, keyed by clip name.
 * Each entry holds the three AUTHORED facings; east is west mirrored at bake
 * time (`facing.ts`), so it is never imported.
 *
 * NOT wired into `rig-catalog.ts` — that is a separate slice.
 */
import type { Clip } from '../rig';
import { CLIP_WALK } from './walk';
import { CLIP_WALK_BRISK } from './walk-brisk';
import { CLIP_WAVE } from './wave';

export { CLIP_WALK } from './walk';
export { CLIP_WALK_BRISK } from './walk-brisk';
export { CLIP_WAVE } from './wave';

export type ImportedClipSet = Readonly<Record<'down' | 'up' | 'left', Clip>>;

export const IMPORTED_CLIPS: Readonly<Record<string, ImportedClipSet>> = {
  'walk': CLIP_WALK,
  'walk-brisk': CLIP_WALK_BRISK,
  'wave': CLIP_WAVE,
};
