/**
 * GENERATED by `npx tsx scripts/motion-import-bvh.ts` — do not hand-edit;
 * re-run to change. Byte-identity is pinned by
 * `tests/unit/motion-import-determinism.test.ts`.
 *
 * Every clip imported from the vendored CMU captures, keyed by clip name.
 * Each entry holds the three AUTHORED facings; east is west mirrored at bake
 * time (`facing.ts`), so it is never imported.
 *
 * `IMPORTED_CLIP_META` is keyed the same way — same ids, one entry each, so a
 * caller holding a clip name can always ask what capture it came from and how
 * fast it wants to be played.
 */
import type { Clip } from '../rig';
import type { ImportedClipMeta } from '../clip-meta';
import { CLIP_WALK, CLIP_WALK_META } from './walk';
import { CLIP_WALK_BRISK, CLIP_WALK_BRISK_META } from './walk-brisk';
import { CLIP_WAVE, CLIP_WAVE_META } from './wave';
import { CLIP_MARCH, CLIP_MARCH_META } from './march';
import { CLIP_DIG, CLIP_DIG_META } from './dig';

export { CLIP_WALK, CLIP_WALK_META } from './walk';
export { CLIP_WALK_BRISK, CLIP_WALK_BRISK_META } from './walk-brisk';
export { CLIP_WAVE, CLIP_WAVE_META } from './wave';
export { CLIP_MARCH, CLIP_MARCH_META } from './march';
export { CLIP_DIG, CLIP_DIG_META } from './dig';

export type ImportedClipSet = Readonly<Record<'down' | 'up' | 'left', Clip>>;

export const IMPORTED_CLIPS: Readonly<Record<string, ImportedClipSet>> = {
  'walk': CLIP_WALK,
  'walk-brisk': CLIP_WALK_BRISK,
  'wave': CLIP_WAVE,
  'march': CLIP_MARCH,
  'dig': CLIP_DIG,
};

export const IMPORTED_CLIP_META: Readonly<Record<string, ImportedClipMeta>> = {
  'walk': CLIP_WALK_META,
  'walk-brisk': CLIP_WALK_BRISK_META,
  'wave': CLIP_WAVE_META,
  'march': CLIP_MARCH_META,
  'dig': CLIP_DIG_META,
};
