/**
 * GENERATED by `npx tsx scripts/motion-import-bvh.ts march` — do not
 * hand-edit; re-run to change. Byte-identity is pinned by
 * `tests/unit/motion-import-determinism.test.ts`.
 *
 * Capture: vendor/mocap/cmu/138_01.bvh — CMU Graphics Lab Motion Capture
 * Database, cgspeed BVH conversion, 120 fps (see CREDITS.md).
 *
 * march, travelling. `--contacts` finds LEFT heel-strike onsets at 208, 361,
 * 508, 654, 796 (gaps 153, 147, 146, 142); `--periods --from 361` confirms it
 * — P=148 minimizes the first/last pose distance (0.374px), one frame off the
 * contact gap, so the loop closes on measurement twice over. Range [361, 509],
 * travelling 38.7px (0.76 figure heights) per cycle — this is a walk-like
 * clip, not stationary. `--sweep` at the default 12 keys: 9 frames sits AT the
 * aliasing edge (8.0deg RMS / 26.6deg peak on legFar_fore, the swing leg
 * outrunning the sample rate); 17 frames clears it with room (2.7deg RMS /
 * 6.3deg peak) and raising maxKeys past 12 moves the number by under 0.5deg —
 * this is aliasing converging with a finer `range` sample, not a keyframe
 * ceiling, so the default cap is left alone. Now importable in the frontal
 * facings at all: their forearm bones are `mode: 'translate'` (see
 * `HUMANOID_BVH_MAP`), so the ±94deg out-of-plane flail this capture used to
 * windmill stays off the rotation channel entirely and rides dx/dy instead —
 * the profile (`left`) facing is untouched and keeps genuine forearm rotation.
 * FRONTAL LEGS TORE ON FIRST IMPORT (M5b follow-up): the ~24deg frontal leg
 * swing — small next to the 61deg the west leg survives, but this is a
 * DIFFERENT rig (the south/north leg chips, rected for the shipped
 * `pray-raise`/`idle-shift`, not for a swing this size) — carried the
 * shin/foot chip clean off the thigh: RAW bake, whole clip, 1104 stray px on
 * down / 919 on up, the worst tearing measured on this rig (against 37 on the
 * pre-M4 west walk). Same mechanism as the west leg and the wave arms, same
 * fix, same discipline: swept `skinBand` 0..10 (RAW bake, `fragmentation`) and
 * read the worst frames at 9x rather than trusting the count (M5b's own trap:
 * a wide band can merge a hole with the outer silhouette instead of filling
 * it). Band 1 alone drops BOTH facings to 0 stray px (down 25 hole, up 19) and
 * the 9x crop shows genuinely REPAIRED legs, not a reclassified gap — band 2+
 * buys nothing (hole count is flat-to-worse: down climbs to
 * 22/26/29/31/36/50/41 at bands 2/3/4/5/6/8/10, up similarly noisy), so 1 is
 * both the smallest and the best-measured. Unlike the wave, this is not the
 * whole story: at `in-plane >= 0.04` (legR_up), the frontal leg swing is
 * mostly a coronal-projection artifact of a capture that travels mostly toward
 * the camera, so even a structurally sound bake reads as a NEAR-STATIONARY
 * march head-on — band 1 fixes the tear, not the flatness. Left for the studio
 * to judge against the render (`tmp/motion/march-sheet.png`), not decided
 * here.
 *
 * Options: range [361, 509] · frames 17 ·
 *   referenceFrame 'mean' ·
 *   loop 'auto' · rootMotion 'in-place' (default) ·
 *   pxPerUnit 1.891445 (51 px figure ÷ T-pose extent 26.964 units)
 *
 * Cycle: 148 source frames = 1.2333 s.
 * Stride: 38.7 px per cycle → IMPLIED GROUND SPEED 31.4 px/s.
 *   The bake is in-place, so the feet slide one stride per cycle and read as
 *   PLANTED only when the NPC actually moves at that speed. That is M2's
 *   tuning knob, not a defect of this bake.
 * Loop residual (capture, first→last pose): 0.37 px RMS per joint.
 *
 * Sampling: 9.25 source frames between baked samples (77.1 ms per frame).
 *   DECIMATION ERROR vs an undecimated bake of the same range: 2.7° RMS,
 *   6.3° peak, worst on armFar_up (left).
 *   That is the whole aliasing question answered by measurement: an under-sampled
 *   wiggle reconstructs to the wrong shape and this number blows up. Re-run the
 *   importer to check it rather than trusting this sentence.
 *
 * Per facing — tracks, worst per-frame angle step, t=0..t=1 gap, plants,
 * and the foreshortening floor (least of any rotating bone in-plane length):
 *   down  10 tracks · max     24° · step  19.5° (legR_up) · loop 0° · 0 plant(s) · in-plane ≥ 0.04 (legR_up)
 *   up    10 tracks · max     24° · step  19.5° (legL_up) · loop 0° · 0 plant(s) · in-plane ≥ 0.04 (legL_up)
 *   left  10 tracks · max   63.5° · step    40° (legNear_fore) · loop 0° · 0 plant(s) · in-plane ≥ 0.84 (armNear_fore)
 *
 * A per-frame step approaching 180° would mean the gesture outran the baked
 * rate and the angle unwrapper picked the wrong branch. A foreshortening
 * floor approaching 0 would mean a bone points at the camera and the rig is
 * rotating a chip on noise. Neither happens here — the captures that DID
 * fail those two reads are listed, with their numbers, in the importer.
 */

import type { Clip } from '../rig';
import type { ImportedClipMeta } from '../clip-meta';

/** Capture facts a player can feel: cadence, travel, and whether it loops. */
export const CLIP_MARCH_META: ImportedClipMeta = {
  source: '138_01.bvh',
  cycleSeconds: 1.2333,
  frameMs: 77.1,
  stridePx: 38.7,
  groundSpeedPxPerSec: 31.4,
  loop: true,
};

export const CLIP_MARCH_DOWN: Clip = {
  name: 'march',
  frames: 17,
  tracks: {
    trunk: [
      { t: 0, deg: 0, dx: 0.5, dy: 0.75 },
      { t: 0.25, deg: 0, dx: 1, dy: -0.5 },
      { t: 0.5, deg: 0, dx: -0.5, dy: 0.75 },
      { t: 0.75, deg: 0, dx: -0.75, dy: -0.75 },
      { t: 0.9375, deg: 0, dx: -0.5, dy: 0.25 },
      { t: 1, deg: 0, dx: 0.5, dy: 0.75 },
    ],
    head: [
      { t: 0, deg: 0, dx: 0 },
      { t: 1, deg: 0, dx: 0 },
    ],
    armL_up: [
      { t: 0, deg: 1, dx: 0, dy: 0 },
      { t: 0.375, deg: 3, dx: 0.25, dy: 0.25 },
      { t: 0.5, deg: -5, dx: 0, dy: 0.25 },
      { t: 0.625, deg: -7, dx: -0.25, dy: 0 },
      { t: 0.8125, deg: 5.5, dx: -0.25, dy: -0.25 },
      { t: 1, deg: 1, dx: 0, dy: 0 },
    ],
    armL_fore: [
      { t: 0, deg: -1, dx: -0.25, dy: 1.75 },
      { t: 0.25, deg: -3, dx: 0, dy: -0.75 },
      { t: 0.375, deg: -3, dx: 0, dy: 0.25 },
      { t: 0.5, deg: 5, dx: 0, dy: 1.25 },
      { t: 0.5625, deg: 7, dx: 0, dy: 0.75 },
      { t: 0.6875, deg: 3.5, dx: 0.25, dy: -1.75 },
      { t: 0.75, deg: -2.5, dx: 0.25, dy: -2.25 },
      { t: 0.8125, deg: -5.5, dx: 0.25, dy: -2 },
      { t: 1, deg: -1, dx: -0.25, dy: 1.75 },
    ],
    armR_up: [
      { t: 0, deg: 4.5, dx: 0, dy: 0.25 },
      { t: 0.0625, deg: 8.5, dx: 0.25, dy: 0.25 },
      { t: 0.25, deg: 2.5, dx: 0, dy: -0.25 },
      { t: 0.5, deg: 2.5, dx: 0, dy: -0.25 },
      { t: 0.8125, deg: -9.5, dx: 0, dy: 0.25 },
      { t: 0.9375, deg: -2.5, dx: 0, dy: 0.25 },
      { t: 1, deg: 4.5, dx: 0, dy: 0.25 },
    ],
    armR_fore: [
      { t: 0, deg: -4.5, dx: 0, dy: 0.25 },
      { t: 0.0625, deg: -8.5, dx: 0, dy: 0.25 },
      { t: 0.25, deg: -2.5, dx: 0, dy: -0.75 },
      { t: 0.5, deg: -2.5, dx: 0, dy: 0.5 },
      { t: 0.8125, deg: 9.5, dx: 0, dy: -0.25 },
      { t: 0.9375, deg: 2.5, dx: 0, dy: 0.25 },
      { t: 1, deg: -4.5, dx: 0, dy: 0.25 },
    ],
    legL_up: [
      { t: 0, deg: 0.5, dx: -0.25, dy: 0 },
      { t: 0.0625, deg: 6, dx: 0.25, dy: 0.25 },
      { t: 0.1875, deg: 10, dx: 0.5, dy: 0.25 },
      { t: 0.25, deg: 10, dx: 0.5, dy: 0.25 },
      { t: 0.3125, deg: 3.5, dx: 0.5, dy: 0.25 },
      { t: 0.5625, deg: -5, dx: -0.25, dy: 0 },
      { t: 0.9375, deg: -4.5, dx: -0.5, dy: -0.25 },
      { t: 1, deg: 0.5, dx: -0.25, dy: 0 },
    ],
    legL_fore: [
      { t: 0, deg: -2, dx: -0.25, dy: 3 },
      { t: 0.0625, deg: -8.5, dx: -0.75, dy: 2.75 },
      { t: 0.125, deg: -4.5, dx: -1.25, dy: -1.75 },
      { t: 0.1875, deg: -5.5, dx: -0.75, dy: -3 },
      { t: 0.25, deg: -8, dx: -0.5, dy: -3 },
      { t: 0.3125, deg: -3.5, dx: -0.25, dy: -3 },
      { t: 0.375, deg: 0, dx: -0.5, dy: -3 },
      { t: 0.5, deg: 6, dx: 0, dy: 1.5 },
      { t: 0.625, deg: 4.5, dx: 0.25, dy: 2.75 },
      { t: 0.875, deg: 4, dx: 0.25, dy: 3 },
      { t: 0.9375, deg: 3, dx: 0.25, dy: 2.75 },
      { t: 1, deg: -2, dx: -0.25, dy: 3 },
    ],
    legR_up: [
      { t: 0, deg: 6, dx: -0.25, dy: 0.25 },
      { t: 0.125, deg: 9.5, dx: 0.5, dy: -0.25 },
      { t: 0.4375, deg: 6, dx: 0.5, dy: -0.25 },
      { t: 0.5625, deg: -2, dx: -0.25, dy: 0.25 },
      { t: 0.625, deg: -7.5, dx: -0.25, dy: 0.25 },
      { t: 0.6875, deg: -21.5, dx: -0.5, dy: 0.25 },
      { t: 0.8125, deg: -22, dx: -0.5, dy: 0.25 },
      { t: 0.875, deg: -2.5, dx: -0.5, dy: 0.25 },
      { t: 1, deg: 6, dx: -0.25, dy: 0.25 },
    ],
    legR_fore: [
      { t: 0, deg: -7.5, dx: 0.5, dy: 2.5 },
      { t: 0.5, deg: -4, dx: 0.75, dy: 3 },
      { t: 0.5625, deg: 1.5, dx: 1.25, dy: 2.75 },
      { t: 0.625, deg: 4.5, dx: 1.25, dy: -1.75 },
      { t: 0.6875, deg: 18.5, dx: 1, dy: -2.75 },
      { t: 0.8125, deg: 24, dx: 0.75, dy: -3 },
      { t: 0.875, deg: 5.5, dx: 0.25, dy: -3 },
      { t: 0.9375, deg: -3, dx: 0.75, dy: -0.25 },
      { t: 1, deg: -7.5, dx: 0.5, dy: 2.5 },
    ],
  },
  skinBand: 1,
};

export const CLIP_MARCH_UP: Clip = {
  name: 'march',
  frames: 17,
  tracks: {
    trunk: [
      { t: 0, deg: 0, dx: -0.5, dy: 0.75 },
      { t: 0.25, deg: 0, dx: -1, dy: -0.5 },
      { t: 0.5, deg: 0, dx: 0.5, dy: 0.75 },
      { t: 0.75, deg: 0, dx: 0.75, dy: -0.75 },
      { t: 0.9375, deg: 0, dx: 0.5, dy: 0.25 },
      { t: 1, deg: 0, dx: -0.5, dy: 0.75 },
    ],
    head: [
      { t: 0, deg: 0, dx: 0 },
      { t: 1, deg: 0, dx: 0 },
    ],
    armL_up: [
      { t: 0, deg: -4.5, dx: 0, dy: 0.25 },
      { t: 0.0625, deg: -8.5, dx: -0.25, dy: 0.25 },
      { t: 0.25, deg: -2.5, dx: 0, dy: -0.25 },
      { t: 0.5, deg: -2.5, dx: 0, dy: -0.25 },
      { t: 0.8125, deg: 9.5, dx: 0, dy: 0.25 },
      { t: 0.9375, deg: 2.5, dx: 0, dy: 0.25 },
      { t: 1, deg: -4.5, dx: 0, dy: 0.25 },
    ],
    armL_fore: [
      { t: 0, deg: 4.5, dx: 0, dy: 0.25 },
      { t: 0.0625, deg: 8.5, dx: 0, dy: 0 },
      { t: 0.25, deg: 2.5, dx: 0, dy: -0.75 },
      { t: 0.5, deg: 2.5, dx: 0, dy: 0.5 },
      { t: 0.8125, deg: -9.5, dx: 0, dy: 0 },
      { t: 0.9375, deg: -2.5, dx: 0, dy: 0.25 },
      { t: 1, deg: 4.5, dx: 0, dy: 0.25 },
    ],
    armR_up: [
      { t: 0, deg: -1, dx: 0, dy: 0 },
      { t: 0.375, deg: -3, dx: -0.25, dy: 0.25 },
      { t: 0.5, deg: 5, dx: 0, dy: 0.25 },
      { t: 0.625, deg: 7, dx: 0.25, dy: 0 },
      { t: 0.8125, deg: -5.5, dx: 0.25, dy: -0.25 },
      { t: 1, deg: -1, dx: 0, dy: 0 },
    ],
    armR_fore: [
      { t: 0, deg: 1, dx: 0.25, dy: 1.75 },
      { t: 0.25, deg: 3, dx: 0, dy: -1 },
      { t: 0.375, deg: 3, dx: 0, dy: 0 },
      { t: 0.5, deg: -5, dx: 0, dy: 1.25 },
      { t: 0.5625, deg: -7, dx: 0, dy: 1 },
      { t: 0.6875, deg: -3.5, dx: -0.25, dy: -1.75 },
      { t: 0.75, deg: 2.5, dx: -0.25, dy: -2.5 },
      { t: 0.8125, deg: 5.5, dx: -0.25, dy: -2 },
      { t: 1, deg: 1, dx: 0.25, dy: 1.75 },
    ],
    legL_up: [
      { t: 0, deg: -6, dx: 0.25, dy: 0.25 },
      { t: 0.125, deg: -9.5, dx: -0.5, dy: -0.25 },
      { t: 0.4375, deg: -6, dx: -0.5, dy: -0.25 },
      { t: 0.5625, deg: 2, dx: 0.25, dy: 0.25 },
      { t: 0.625, deg: 7.5, dx: 0.25, dy: 0.25 },
      { t: 0.6875, deg: 21.5, dx: 0.5, dy: 0.25 },
      { t: 0.8125, deg: 22, dx: 0.5, dy: 0.25 },
      { t: 0.875, deg: 2.5, dx: 0.5, dy: 0.25 },
      { t: 1, deg: -6, dx: 0.25, dy: 0.25 },
    ],
    legL_fore: [
      { t: 0, deg: 7.5, dx: -0.5, dy: 2.5 },
      { t: 0.5, deg: 4, dx: -0.75, dy: 3 },
      { t: 0.5625, deg: -1.5, dx: -1.25, dy: 2.75 },
      { t: 0.625, deg: -4.5, dx: -1.25, dy: -1.75 },
      { t: 0.6875, deg: -18.5, dx: -1, dy: -2.75 },
      { t: 0.8125, deg: -24, dx: -0.75, dy: -3 },
      { t: 0.875, deg: -5.5, dx: -0.25, dy: -3 },
      { t: 0.9375, deg: 3, dx: -0.75, dy: -0.25 },
      { t: 1, deg: 7.5, dx: -0.5, dy: 2.5 },
    ],
    legR_up: [
      { t: 0, deg: -0.5, dx: 0.25, dy: 0 },
      { t: 0.0625, deg: -6, dx: -0.25, dy: 0.25 },
      { t: 0.1875, deg: -10, dx: -0.5, dy: 0.25 },
      { t: 0.25, deg: -10, dx: -0.5, dy: 0.25 },
      { t: 0.3125, deg: -3.5, dx: -0.5, dy: 0.25 },
      { t: 0.5625, deg: 5, dx: 0.25, dy: 0 },
      { t: 0.9375, deg: 4.5, dx: 0.5, dy: -0.25 },
      { t: 1, deg: -0.5, dx: 0.25, dy: 0 },
    ],
    legR_fore: [
      { t: 0, deg: 2, dx: 0.25, dy: 3 },
      { t: 0.0625, deg: 8.5, dx: 0.75, dy: 2.75 },
      { t: 0.125, deg: 4.5, dx: 1.25, dy: -1.75 },
      { t: 0.1875, deg: 5.5, dx: 0.75, dy: -3 },
      { t: 0.25, deg: 8, dx: 0.5, dy: -3 },
      { t: 0.3125, deg: 3.5, dx: 0.25, dy: -3 },
      { t: 0.375, deg: 0, dx: 0.5, dy: -3 },
      { t: 0.5, deg: -6, dx: 0, dy: 1.5 },
      { t: 0.625, deg: -4.5, dx: -0.25, dy: 2.75 },
      { t: 0.875, deg: -4, dx: -0.25, dy: 3 },
      { t: 0.9375, deg: -3, dx: -0.25, dy: 2.75 },
      { t: 1, deg: 2, dx: 0.25, dy: 3 },
    ],
  },
  skinBand: 1,
};

export const CLIP_MARCH_LEFT: Clip = {
  name: 'march',
  frames: 17,
  tracks: {
    trunk: [
      { t: 0, deg: 0, dx: 0.5, dy: 0.75 },
      { t: 0.125, deg: 0, dx: -0.25, dy: 0 },
      { t: 0.25, deg: 0, dx: 0.5, dy: -0.5 },
      { t: 0.4375, deg: 0, dx: 1.5, dy: 0.5 },
      { t: 0.5, deg: 0, dx: -0.25, dy: 0.75 },
      { t: 0.625, deg: 0, dx: -1.5, dy: -0.25 },
      { t: 0.8125, deg: 0, dx: -0.5, dy: -0.5 },
      { t: 1, deg: 0, dx: 0.5, dy: 0.75 },
    ],
    head: [
      { t: 0, deg: 0.5, dx: 0.75 },
      { t: 0.25, deg: 0.5, dx: -0.25 },
      { t: 0.6875, deg: -1, dx: -0.25 },
      { t: 1, deg: 0.5, dx: 0.75 },
    ],
    armNear_up: [
      { t: 0, deg: -9, dx: 1, dy: 0.25 },
      { t: 0.0625, deg: 4.5, dx: 0.5, dy: 0.25 },
      { t: 0.125, deg: 18.5, dx: -0.25, dy: 0 },
      { t: 0.25, deg: 36, dx: -1.25, dy: -0.25 },
      { t: 0.375, deg: 31, dx: -1.25, dy: -0.25 },
      { t: 0.4375, deg: 23, dx: -0.5, dy: -0.25 },
      { t: 0.5625, deg: -0.5, dx: -0.25, dy: -0.25 },
      { t: 0.625, deg: -15, dx: 0, dy: 0 },
      { t: 0.75, deg: -35.5, dx: 0.75, dy: 0.25 },
      { t: 0.875, deg: -31, dx: 0.75, dy: 0.25 },
      { t: 0.9375, deg: -23, dx: 0.75, dy: 0.25 },
      { t: 1, deg: -9, dx: 1, dy: 0.25 },
    ],
    armNear_fore: [
      { t: 0, deg: -9, dx: 0.25, dy: 1 },
      { t: 0.125, deg: 12.5, dx: -0.25, dy: 0.75 },
      { t: 0.1875, deg: 17.5, dx: -0.5, dy: 0.75 },
      { t: 0.3125, deg: 19.5, dx: -0.5, dy: 0.75 },
      { t: 0.4375, deg: 14.5, dx: -0.25, dy: 0.75 },
      { t: 0.5, deg: 3.5, dx: -0.25, dy: 0.75 },
      { t: 0.5625, deg: -11.5, dx: 0, dy: 0.75 },
      { t: 0.625, deg: -16.5, dx: 0.25, dy: 1 },
      { t: 0.8125, deg: -15, dx: 0.5, dy: 1.25 },
      { t: 1, deg: -9, dx: 0.25, dy: 1 },
    ],
    armFar_up: [
      { t: 0, deg: 7.5, dx: 0.75, dy: 0 },
      { t: 0.0625, deg: -13, dx: 0.25, dy: 0 },
      { t: 0.125, deg: -31, dx: 0.25, dy: 0 },
      { t: 0.25, deg: -48, dx: 0.5, dy: 0.25 },
      { t: 0.4375, deg: -28, dx: 0.5, dy: 0.25 },
      { t: 0.5, deg: -11, dx: 0.25, dy: 0.25 },
      { t: 0.5625, deg: 8.5, dx: 0, dy: 0.25 },
      { t: 0.625, deg: 27.5, dx: -0.5, dy: 0 },
      { t: 0.75, deg: 51.5, dx: -1, dy: -0.25 },
      { t: 0.875, deg: 40.5, dx: -0.75, dy: -0.25 },
      { t: 0.9375, deg: 26.5, dx: 0, dy: -0.25 },
      { t: 1, deg: 7.5, dx: 0.75, dy: 0 },
    ],
    armFar_fore: [
      { t: 0, deg: -2, dx: -0.25, dy: 1.75 },
      { t: 0.0625, deg: -8, dx: 0.25, dy: 2 },
      { t: 0.3125, deg: -4, dx: 1, dy: 2.75 },
      { t: 0.5, deg: -8, dx: 0.25, dy: 2 },
      { t: 0.625, deg: 10, dx: -1, dy: 1.75 },
      { t: 0.6875, deg: 12, dx: -1.5, dy: 2 },
      { t: 0.9375, deg: 4, dx: -1, dy: 1.75 },
      { t: 1, deg: -2, dx: -0.25, dy: 1.75 },
    ],
    legNear_up: [
      { t: 0, deg: -6, dx: 0, dy: 0.25 },
      { t: 0.125, deg: -21, dx: 0.25, dy: -0.25 },
      { t: 0.1875, deg: -26.5, dx: 0.25, dy: -0.25 },
      { t: 0.25, deg: -31, dx: 0, dy: -0.25 },
      { t: 0.4375, deg: -43, dx: 0.5, dy: -0.25 },
      { t: 0.75, deg: 63.5, dx: -0.5, dy: 0.25 },
      { t: 0.8125, deg: 60.5, dx: -0.25, dy: 0.25 },
      { t: 0.875, deg: 42, dx: -0.25, dy: 0.25 },
      { t: 1, deg: -6, dx: 0, dy: 0.25 },
    ],
    legNear_fore: [
      { t: 0, deg: 8, dx: -0.75, dy: 2.5 },
      { t: 0.1875, deg: 24.5, dx: 0.5, dy: 3 },
      { t: 0.4375, deg: 22.5, dx: 0.5, dy: 3 },
      { t: 0.5, deg: 0.5, dx: 0.5, dy: 3 },
      { t: 0.5625, deg: -39.5, dx: -0.75, dy: 2.5 },
      { t: 0.625, deg: -22.5, dx: -3, dy: 0.25 },
      { t: 0.6875, deg: -11.5, dx: -3, dy: 0.25 },
      { t: 0.75, deg: -14, dx: -3, dy: 0.25 },
      { t: 0.8125, deg: -25.5, dx: -3, dy: 0.25 },
      { t: 0.875, deg: -42, dx: -3, dy: 0.25 },
      { t: 0.9375, deg: -13.5, dx: -2.75, dy: 0.75 },
      { t: 1, deg: 8, dx: -0.75, dy: 2.5 },
    ],
    legFar_up: [
      { t: 0, deg: -31.5, dx: 0.5, dy: 0 },
      { t: 0.0625, deg: -7, dx: 0, dy: 0.25 },
      { t: 0.125, deg: 24.5, dx: -0.25, dy: 0.25 },
      { t: 0.1875, deg: 47, dx: -0.5, dy: 0.25 },
      { t: 0.25, deg: 56.5, dx: -0.5, dy: 0.25 },
      { t: 0.3125, deg: 52.5, dx: -0.25, dy: 0.25 },
      { t: 0.375, deg: 37, dx: -0.25, dy: 0.5 },
      { t: 0.4375, deg: 15, dx: -0.25, dy: 0.5 },
      { t: 0.5, deg: 1.5, dx: 0, dy: 0.25 },
      { t: 0.6875, deg: -20.5, dx: 0, dy: -0.5 },
      { t: 0.9375, deg: -38.5, dx: 0.5, dy: -0.25 },
      { t: 1, deg: -31.5, dx: 0.5, dy: 0 },
    ],
    legFar_fore: [
      { t: 0, deg: 5, dx: 0.75, dy: 3 },
      { t: 0.0625, deg: -33.5, dx: -0.25, dy: 2.75 },
      { t: 0.125, deg: -25, dx: -3, dy: -0.5 },
      { t: 0.1875, deg: -19.5, dx: -3, dy: -0.5 },
      { t: 0.3125, deg: -43.5, dx: -3, dy: -0.25 },
      { t: 0.4375, deg: -2, dx: -3, dy: 0.25 },
      { t: 0.5, deg: 8, dx: -1.25, dy: 1.5 },
      { t: 0.5625, deg: 11.5, dx: -0.5, dy: 2.5 },
      { t: 0.625, deg: 20.5, dx: 0.25, dy: 3 },
      { t: 0.6875, deg: 25.5, dx: 0.5, dy: 3 },
      { t: 0.9375, deg: 26, dx: 0.75, dy: 3 },
      { t: 1, deg: 5, dx: 0.75, dy: 3 },
    ],
  },
};

/** The three AUTHORED facings; east is west mirrored at bake time (`facing.ts`). */
export const CLIP_MARCH: Readonly<Record<'down' | 'up' | 'left', Clip>> = {
  down: CLIP_MARCH_DOWN,
  up: CLIP_MARCH_UP,
  left: CLIP_MARCH_LEFT,
};
