/**
 * GENERATED by `npx tsx scripts/motion-import-bvh.ts walk-brisk` — do not
 * hand-edit; re-run to change. Byte-identity is pinned by
 * `tests/unit/motion-import-determinism.test.ts`.
 *
 * Capture: vendor/mocap/cmu/07_01.bvh — CMU Graphics Lab Motion Capture
 * Database, cgspeed BVH conversion, 120 fps (see CREDITS.md).
 *
 * a faster walk by the same measure — 0.6 s per step against 104_02's 0.7 s,
 * and a stride 32% longer. Cycle from the RIGHT heel strike at 130; 127 frames
 * is the pose-distance minimum over 90..180 (the foot-contact spacing says
 * 131, and the 4-frame disagreement is the capture decelerating slightly).
 *
 * Options: range [130, 257] · frames 9 ·
 *   referenceFrame 'mean' ·
 *   loop 'auto' · rootMotion 'in-place' (default) ·
 *   pxPerUnit 2.000213 (51 px figure ÷ T-pose extent 25.497 units)
 *
 * Cycle: 127 source frames = 1.0583 s.
 * Stride: 52.3 px per cycle → IMPLIED GROUND SPEED 49.4 px/s.
 *   The bake is in-place, so the feet slide one stride per cycle and read as
 *   PLANTED only when the NPC actually moves at that speed. That is M2's
 *   tuning knob, not a defect of this bake.
 * Loop residual (capture, first→last pose): 0.63 px RMS per joint.
 *
 * Per facing — tracks, worst per-frame angle step, t=0..t=1 gap, plants,
 * and the foreshortening floor (least of any rotating bone in-plane length):
 *   down  10 tracks · max   22.5° · step    24° (legR_fore) · loop 0° · 0 plant(s) · in-plane ≥ 0.44 (armR_fore)
 *   up    10 tracks · max   22.5° · step    24° (legL_fore) · loop 0° · 0 plant(s) · in-plane ≥ 0.44 (armL_fore)
 *   left  10 tracks · max   40.5° · step    54° (legFar_fore) · loop 0° · 0 plant(s) · in-plane ≥ 0.97 (armFar_up)
 *
 * A per-frame step approaching 180° would mean the gesture outran the baked
 * rate and the angle unwrapper picked the wrong branch. A foreshortening
 * floor approaching 0 would mean a bone points at the camera and the rig is
 * rotating a chip on noise. Neither happens here — the captures that DID
 * fail those two reads are listed, with their numbers, in the importer.
 */

import type { Clip } from '../rig';

export const CLIP_WALK_BRISK_DOWN: Clip = {
  name: 'walk-brisk',
  frames: 9,
  tracks: {
    trunk: [
      { t: 0, deg: 0, dx: 0, dy: 1.25 },
      { t: 0.25, deg: 0, dx: -0.5, dy: -0.25 },
      { t: 0.5, deg: 0, dx: 0, dy: 0.5 },
      { t: 0.75, deg: 0, dx: 0.75, dy: -1.25 },
      { t: 1, deg: 0, dx: 0, dy: 1.25 },
    ],
    head: [
      { t: 0, deg: 0, dx: 0 },
      { t: 1, deg: 0, dx: 0 },
    ],
    armL_up: [
      { t: 0, deg: -4.5, dx: 0, dy: 0 },
      { t: 0.5, deg: 7, dx: 0, dy: -0.25 },
      { t: 0.875, deg: -0.5, dx: 0, dy: 0 },
      { t: 1, deg: -4.5, dx: 0, dy: 0 },
    ],
    armL_fore: [
      { t: 0, deg: 11.5, dx: 0.25, dy: -0.75 },
      { t: 0.125, deg: 14, dx: 0.25, dy: -0.5 },
      { t: 0.25, deg: 5, dx: 0, dy: 0.25 },
      { t: 0.375, deg: -12, dx: -0.25, dy: 0.75 },
      { t: 0.5, deg: -19, dx: -0.25, dy: 0.75 },
      { t: 0.625, deg: -9, dx: -0.25, dy: 0.5 },
      { t: 0.75, deg: 0, dx: 0, dy: 0.25 },
      { t: 0.875, deg: 2, dx: 0, dy: -0.25 },
      { t: 1, deg: 11.5, dx: 0.25, dy: -0.75 },
    ],
    armR_up: [
      { t: 0, deg: -2.5, dx: 0, dy: 0 },
      { t: 0.625, deg: 3, dx: 0, dy: 0.25 },
      { t: 1, deg: -2.5, dx: 0, dy: 0 },
    ],
    armR_fore: [
      { t: 0, deg: 22.5, dx: 0, dy: 0 },
      { t: 0.125, deg: 10, dx: 0, dy: 0.5 },
      { t: 0.25, deg: -8.5, dx: 0, dy: 0.5 },
      { t: 0.375, deg: -16.5, dx: 0, dy: 0 },
      { t: 0.625, deg: -15.5, dx: -0.25, dy: -0.25 },
      { t: 0.75, deg: -11.5, dx: 0, dy: 0.5 },
      { t: 1, deg: 22.5, dx: 0, dy: 0 },
    ],
    legL_up: [
      { t: 0, deg: -1, dx: 0.5, dy: 0.25 },
      { t: 0.5, deg: -1.5, dx: -0.5, dy: -0.25 },
      { t: 0.625, deg: 6, dx: 0, dy: 0.25 },
      { t: 1, deg: -1, dx: 0.5, dy: 0.25 },
    ],
    legL_fore: [
      { t: 0, deg: 6, dx: 0, dy: -1.25 },
      { t: 0.25, deg: 1.5, dx: 0.5, dy: 1 },
      { t: 0.375, deg: 0.5, dx: 0.5, dy: 0.75 },
      { t: 0.5, deg: 2.5, dx: 0.25, dy: -0.75 },
      { t: 0.625, deg: -14, dx: -0.75, dy: 1.5 },
      { t: 0.75, deg: -9.5, dx: -0.75, dy: 0.5 },
      { t: 0.875, deg: 6, dx: 0, dy: -0.75 },
      { t: 1, deg: 6, dx: 0, dy: -1.25 },
    ],
    legR_up: [
      { t: 0, deg: 2.5, dx: 0.5, dy: -0.25 },
      { t: 0.125, deg: -6.5, dx: 0, dy: 0.25 },
      { t: 0.5, deg: 0.5, dx: -0.5, dy: 0.5 },
      { t: 0.625, deg: 2, dx: 0, dy: -0.25 },
      { t: 1, deg: 2.5, dx: 0.5, dy: -0.25 },
    ],
    legR_fore: [
      { t: 0, deg: -5, dx: -0.25, dy: -0.5 },
      { t: 0.125, deg: 19, dx: 0.75, dy: 1.25 },
      { t: 0.25, deg: 11.5, dx: 0.75, dy: 0.25 },
      { t: 0.375, deg: -4, dx: 0.25, dy: -0.75 },
      { t: 0.5, deg: -5.5, dx: 0, dy: -1.25 },
      { t: 0.75, deg: -4.5, dx: -0.5, dy: 1 },
      { t: 0.875, deg: -4, dx: -0.5, dy: 0.75 },
      { t: 1, deg: -5, dx: -0.25, dy: -0.5 },
    ],
  },
};

export const CLIP_WALK_BRISK_UP: Clip = {
  name: 'walk-brisk',
  frames: 9,
  tracks: {
    trunk: [
      { t: 0, deg: 0, dx: 0, dy: 1.25 },
      { t: 0.25, deg: 0, dx: 0.5, dy: -0.25 },
      { t: 0.5, deg: 0, dx: 0, dy: 0.5 },
      { t: 0.75, deg: 0, dx: -0.75, dy: -1.25 },
      { t: 1, deg: 0, dx: 0, dy: 1.25 },
    ],
    head: [
      { t: 0, deg: 0, dx: 0 },
      { t: 1, deg: 0, dx: 0 },
    ],
    armL_up: [
      { t: 0, deg: 2.5, dx: 0, dy: 0 },
      { t: 0.625, deg: -3, dx: 0, dy: 0.25 },
      { t: 1, deg: 2.5, dx: 0, dy: 0 },
    ],
    armL_fore: [
      { t: 0, deg: -22.5, dx: 0, dy: 0 },
      { t: 0.125, deg: -10, dx: 0, dy: 0.5 },
      { t: 0.25, deg: 8.5, dx: 0, dy: 0.5 },
      { t: 0.375, deg: 16.5, dx: 0, dy: 0 },
      { t: 0.625, deg: 15.5, dx: 0.25, dy: -0.25 },
      { t: 0.75, deg: 11.5, dx: 0, dy: 0.5 },
      { t: 1, deg: -22.5, dx: 0, dy: 0 },
    ],
    armR_up: [
      { t: 0, deg: 4.5, dx: 0, dy: 0 },
      { t: 0.5, deg: -7, dx: 0, dy: -0.25 },
      { t: 0.875, deg: 0.5, dx: 0, dy: 0 },
      { t: 1, deg: 4.5, dx: 0, dy: 0 },
    ],
    armR_fore: [
      { t: 0, deg: -11.5, dx: -0.25, dy: -0.75 },
      { t: 0.125, deg: -14, dx: -0.25, dy: -0.25 },
      { t: 0.25, deg: -5, dx: 0, dy: 0.25 },
      { t: 0.375, deg: 12, dx: 0.25, dy: 0.75 },
      { t: 0.5, deg: 19, dx: 0.25, dy: 0.75 },
      { t: 0.625, deg: 9, dx: 0.25, dy: 0.5 },
      { t: 0.75, deg: 0, dx: 0, dy: 0.25 },
      { t: 0.875, deg: -2, dx: 0, dy: -0.25 },
      { t: 1, deg: -11.5, dx: -0.25, dy: -0.75 },
    ],
    legL_up: [
      { t: 0, deg: -2.5, dx: -0.5, dy: -0.25 },
      { t: 0.125, deg: 6.5, dx: 0, dy: 0.25 },
      { t: 0.5, deg: -0.5, dx: 0.5, dy: 0.5 },
      { t: 0.625, deg: -2, dx: 0, dy: -0.25 },
      { t: 1, deg: -2.5, dx: -0.5, dy: -0.25 },
    ],
    legL_fore: [
      { t: 0, deg: 5, dx: 0.25, dy: -0.5 },
      { t: 0.125, deg: -19, dx: -0.75, dy: 1.25 },
      { t: 0.25, deg: -11.5, dx: -0.75, dy: 0.25 },
      { t: 0.375, deg: 4, dx: -0.25, dy: -0.75 },
      { t: 0.5, deg: 5.5, dx: 0, dy: -1.25 },
      { t: 0.75, deg: 4.5, dx: 0.5, dy: 1 },
      { t: 0.875, deg: 4, dx: 0.5, dy: 0.75 },
      { t: 1, deg: 5, dx: 0.25, dy: -0.5 },
    ],
    legR_up: [
      { t: 0, deg: 1, dx: -0.5, dy: 0.25 },
      { t: 0.5, deg: 1.5, dx: 0.5, dy: -0.25 },
      { t: 0.625, deg: -6, dx: 0, dy: 0.25 },
      { t: 1, deg: 1, dx: -0.5, dy: 0.25 },
    ],
    legR_fore: [
      { t: 0, deg: -6, dx: 0, dy: -1.25 },
      { t: 0.25, deg: -1.5, dx: -0.5, dy: 1 },
      { t: 0.375, deg: -0.5, dx: -0.5, dy: 0.75 },
      { t: 0.5, deg: -2.5, dx: -0.25, dy: -0.75 },
      { t: 0.625, deg: 14, dx: 0.75, dy: 1.5 },
      { t: 0.75, deg: 9.5, dx: 0.75, dy: 0.5 },
      { t: 0.875, deg: -6, dx: 0, dy: -0.75 },
      { t: 1, deg: -6, dx: 0, dy: -1.25 },
    ],
  },
};

export const CLIP_WALK_BRISK_LEFT: Clip = {
  name: 'walk-brisk',
  frames: 9,
  tracks: {
    trunk: [
      { t: 0, deg: 0, dx: 26, dy: 1.25 },
      { t: 0.125, deg: 0, dx: 26.75, dy: 0.25 },
      { t: 0.25, deg: 0, dx: 26, dy: -0.25 },
      { t: 0.375, deg: 0, dx: 26.25, dy: 0 },
      { t: 0.5, deg: 0, dx: 28.5, dy: 0.5 },
      { t: 0.625, deg: 0, dx: 26, dy: -0.25 },
      { t: 0.75, deg: 0, dx: 25.25, dy: -1.25 },
      { t: 0.875, deg: 0, dx: 24.5, dy: -0.25 },
      { t: 1, deg: 0, dx: 26, dy: 1.25 },
    ],
    head: [
      { t: 0, deg: 0, dx: 0 },
      { t: 0.625, deg: 2, dx: 0 },
      { t: 0.75, deg: -2, dx: 0 },
      { t: 1, deg: 0, dx: 0 },
    ],
    armNear_up: [
      { t: 0, deg: 21, dx: -0.25, dy: 0 },
      { t: 0.125, deg: 9.5, dx: -0.25, dy: -0.25 },
      { t: 0.25, deg: -3, dx: 0.25, dy: 0 },
      { t: 0.375, deg: -20, dx: 0, dy: 0 },
      { t: 0.5, deg: -27, dx: 0.25, dy: 0.25 },
      { t: 0.625, deg: -20.5, dx: 0.25, dy: 0.25 },
      { t: 0.75, deg: -3, dx: -0.25, dy: 0 },
      { t: 0.875, deg: 15.5, dx: -0.5, dy: 0 },
      { t: 1, deg: 21, dx: -0.25, dy: 0 },
    ],
    armNear_fore: [
      { t: 0, deg: 19, dx: -1, dy: 0 },
      { t: 0.125, deg: 15, dx: -0.5, dy: 0.25 },
      { t: 0.375, deg: -11.5, dx: 0.75, dy: 1.25 },
      { t: 0.5, deg: -19.5, dx: 1, dy: 1.5 },
      { t: 0.625, deg: -17, dx: 0.75, dy: 1.25 },
      { t: 0.75, deg: -6.5, dx: 0, dy: 0.5 },
      { t: 0.875, deg: 6, dx: -0.75, dy: 0.25 },
      { t: 1, deg: 19, dx: -1, dy: 0 },
    ],
    armFar_up: [
      { t: 0, deg: -13.5, dx: 0.5, dy: 0 },
      { t: 0.5, deg: 16.5, dx: -0.75, dy: -0.25 },
      { t: 1, deg: -13.5, dx: 0.5, dy: 0 },
    ],
    armFar_fore: [
      { t: 0, deg: -10, dx: 0.75, dy: 0 },
      { t: 0.125, deg: -16, dx: 0.5, dy: 0.25 },
      { t: 0.25, deg: -5.5, dx: 0, dy: 0.25 },
      { t: 0.375, deg: 9, dx: -0.75, dy: 0.5 },
      { t: 0.5, deg: 15, dx: -0.75, dy: 0.5 },
      { t: 0.625, deg: 11.5, dx: -0.5, dy: 0.5 },
      { t: 0.75, deg: 2.5, dx: -0.25, dy: 0.25 },
      { t: 0.875, deg: 4.5, dx: 0.5, dy: 0 },
      { t: 1, deg: -10, dx: 0.75, dy: 0 },
    ],
    legNear_up: [
      { t: 0, deg: -34, dx: 0.25, dy: -0.25 },
      { t: 0.125, deg: -10.5, dx: 0.25, dy: 0.25 },
      { t: 0.25, deg: 17.5, dx: 0, dy: 0.25 },
      { t: 0.375, deg: 26.5, dx: -0.25, dy: 0.5 },
      { t: 0.5, deg: 28.5, dx: -0.25, dy: 0.5 },
      { t: 0.625, deg: 18, dx: -0.5, dy: -0.25 },
      { t: 0.75, deg: 1, dx: -0.25, dy: 0 },
      { t: 0.875, deg: -15.5, dx: 0.25, dy: -0.25 },
      { t: 1, deg: -34, dx: 0.25, dy: -0.25 },
    ],
    legNear_fore: [
      { t: 0, deg: 24.5, dx: 2.5, dy: 1.75 },
      { t: 0.125, deg: -29, dx: 1.5, dy: 1.5 },
      { t: 0.25, deg: -40.5, dx: -2.75, dy: 1 },
      { t: 0.375, deg: 0, dx: -2.75, dy: 1 },
      { t: 0.5, deg: 0.5, dx: -2.75, dy: 1 },
      { t: 0.625, deg: -3.5, dx: -2.75, dy: 1 },
      { t: 0.75, deg: 7, dx: -0.25, dy: 1 },
      { t: 0.875, deg: 16.5, dx: 2, dy: 1.75 },
      { t: 1, deg: 24.5, dx: 2.5, dy: 1.75 },
    ],
    legFar_up: [
      { t: 0, deg: 23.5, dx: -0.25, dy: 0.25 },
      { t: 0.25, deg: -6, dx: 0, dy: -0.25 },
      { t: 0.375, deg: -22, dx: 0.5, dy: -0.25 },
      { t: 0.5, deg: -40, dx: 0.5, dy: -0.25 },
      { t: 0.75, deg: 9.5, dx: 0, dy: 0 },
      { t: 0.875, deg: 20.5, dx: -0.25, dy: 0.25 },
      { t: 1, deg: 23.5, dx: -0.25, dy: 0.25 },
    ],
    legFar_fore: [
      { t: 0, deg: 0, dx: -3, dy: 0 },
      { t: 0.125, deg: -1, dx: -1.75, dy: 0.25 },
      { t: 0.25, deg: 7.5, dx: 0.75, dy: 1.5 },
      { t: 0.375, deg: 19.5, dx: 2, dy: 2.25 },
      { t: 0.5, deg: 31, dx: 1.75, dy: 2.25 },
      { t: 0.625, deg: -23, dx: 2, dy: 2.25 },
      { t: 0.75, deg: -36, dx: -1.75, dy: 0.25 },
      { t: 0.875, deg: -2, dx: -3, dy: 0 },
      { t: 1, deg: 0, dx: -3, dy: 0 },
    ],
  },
};

/** The three AUTHORED facings; east is west mirrored at bake time (`facing.ts`). */
export const CLIP_WALK_BRISK: Readonly<Record<'down' | 'up' | 'left', Clip>> = {
  down: CLIP_WALK_BRISK_DOWN,
  up: CLIP_WALK_BRISK_UP,
  left: CLIP_WALK_BRISK_LEFT,
};
