/**
 * GENERATED by `npx tsx scripts/motion-import-bvh.ts walk` — do not
 * hand-edit; re-run to change. Byte-identity is pinned by
 * `tests/unit/motion-import-determinism.test.ts`.
 *
 * Capture: vendor/mocap/cmu/104_02.bvh — CMU Graphics Lab Motion Capture
 * Database, cgspeed BVH conversion, 120 fps (see CREDITS.md).
 *
 * neutral-male walk. One gait cycle between successive LEFT heel strikes
 * (stance runs start 214 and 363); 147 frames also minimizes the first/last
 * pose distance over 110..200, so the loop closes on measurement, not on hope.
 *
 * Options: range [214, 361] · frames 9 ·
 *   referenceFrame 'mean' ·
 *   loop 'auto' · rootMotion 'in-place' (default) ·
 *   pxPerUnit 1.948039 (51 px figure ÷ T-pose extent 26.18 units)
 *
 * Cycle: 147 source frames = 1.225 s.
 * Stride: 39.5 px per cycle → IMPLIED GROUND SPEED 32.2 px/s.
 *   The bake is in-place, so the feet slide one stride per cycle and read as
 *   PLANTED only when the NPC actually moves at that speed. That is M2's
 *   tuning knob, not a defect of this bake.
 * Loop residual (capture, first→last pose): 0.37 px RMS per joint.
 *
 * Sampling: 18.38 source frames between baked samples (153.1 ms per frame).
 *   DECIMATION ERROR vs an undecimated bake of the same range: 5.6° RMS,
 *   19.4° peak, worst on legFar_fore (left).
 *   That is the whole aliasing question answered by measurement: an under-sampled
 *   wiggle reconstructs to the wrong shape and this number blows up. Re-run the
 *   importer to check it rather than trusting this sentence.
 *
 * Per facing — tracks, worst per-frame angle step, t=0..t=1 gap, plants,
 * and the foreshortening floor (least of any rotating bone in-plane length):
 *   down  10 tracks · max     21° · step    14° (armL_fore) · loop 0° · 0 plant(s) · in-plane ≥ 0.54 (legR_fore)
 *   up    10 tracks · max     21° · step    14° (armR_fore) · loop 0° · 0 plant(s) · in-plane ≥ 0.54 (legL_fore)
 *   left  10 tracks · max   45.5° · step  68.5° (legFar_fore) · loop 0° · 0 plant(s) · in-plane ≥ 0.98 (armNear_fore)
 *
 * A per-frame step approaching 180° would mean the gesture outran the baked
 * rate and the angle unwrapper picked the wrong branch. A foreshortening
 * floor approaching 0 would mean a bone points at the camera and the rig is
 * rotating a chip on noise. Neither happens here — the captures that DID
 * fail those two reads are listed, with their numbers, in the importer.
 */

import type { Clip } from '../rig';

export const CLIP_WALK_DOWN: Clip = {
  name: 'walk',
  frames: 9,
  tracks: {
    trunk: [
      { t: 0, deg: 0, dx: -1, dy: 0.25 },
      { t: 0.25, deg: 0, dx: 0, dy: -0.25 },
      { t: 0.625, deg: 0, dx: -0.75, dy: 0.25 },
      { t: 0.75, deg: 0, dx: -1, dy: -0.5 },
      { t: 1, deg: 0, dx: -1, dy: 0.25 },
    ],
    head: [
      { t: 0, deg: 0, dx: 0 },
      { t: 0.25, deg: 0, dx: 0.5 },
      { t: 1, deg: 0, dx: 0 },
    ],
    armL_up: [
      { t: 0, deg: 2, dx: -0.25, dy: -0.25 },
      { t: 0.625, deg: -4, dx: 0, dy: 0.5 },
      { t: 1, deg: 2, dx: -0.25, dy: -0.25 },
    ],
    armL_fore: [
      { t: 0, deg: -13.5, dx: 0, dy: 0.25 },
      { t: 0.125, deg: -8.5, dx: 0, dy: 0.5 },
      { t: 0.25, deg: 5.5, dx: 0, dy: 0.25 },
      { t: 0.5, deg: 15, dx: 0.25, dy: -1 },
      { t: 0.625, deg: 13, dx: 0.25, dy: -0.5 },
      { t: 0.75, deg: 3.5, dx: 0, dy: 0 },
      { t: 0.875, deg: -9, dx: 0, dy: 0.5 },
      { t: 1, deg: -13.5, dx: 0, dy: 0.25 },
    ],
    armR_up: [
      { t: 0, deg: 3.5, dx: -0.25, dy: 0.25 },
      { t: 0.5, deg: -4, dx: 0.25, dy: -0.25 },
      { t: 0.875, deg: -1, dx: -0.25, dy: 0 },
      { t: 1, deg: 3.5, dx: -0.25, dy: 0.25 },
    ],
    armR_fore: [
      { t: 0, deg: -10.5, dx: -0.25, dy: -0.75 },
      { t: 0.125, deg: -9, dx: -0.25, dy: -0.25 },
      { t: 0.375, deg: 17.5, dx: 0.25, dy: 0.5 },
      { t: 0.5, deg: 21, dx: 0.25, dy: 0.5 },
      { t: 0.75, deg: -6, dx: 0, dy: 0.25 },
      { t: 1, deg: -10.5, dx: -0.25, dy: -0.75 },
    ],
    legL_up: [
      { t: 0, deg: -4, dx: -0.5, dy: -0.25 },
      { t: 0.25, deg: 5, dx: 0.25, dy: 0.25 },
      { t: 0.5, deg: 3, dx: 0.75, dy: 0.5 },
      { t: 0.625, deg: 0, dx: 0.25, dy: 0.25 },
      { t: 1, deg: -4, dx: -0.5, dy: -0.25 },
    ],
    legL_fore: [
      { t: 0, deg: 1.5, dx: 0.5, dy: 0.25 },
      { t: 0.125, deg: 1.5, dx: 0, dy: -0.75 },
      { t: 0.25, deg: -4, dx: -0.5, dy: 1 },
      { t: 0.375, deg: -3.5, dx: -0.5, dy: -0.75 },
      { t: 0.5, deg: -0.5, dx: -0.5, dy: -1 },
      { t: 0.75, deg: 0.5, dx: 0.25, dy: 1 },
      { t: 1, deg: 1.5, dx: 0.5, dy: 0.25 },
    ],
    legR_up: [
      { t: 0, deg: -2, dx: -0.5, dy: 0.5 },
      { t: 0.25, deg: 3.5, dx: 0.25, dy: -0.5 },
      { t: 0.5, deg: 4.5, dx: 0.75, dy: -0.5 },
      { t: 0.625, deg: 2, dx: 0.25, dy: -0.25 },
      { t: 0.75, deg: -4.5, dx: -0.25, dy: 0.25 },
      { t: 0.875, deg: -6.5, dx: -0.25, dy: 0.25 },
      { t: 1, deg: -2, dx: -0.5, dy: 0.5 },
    ],
    legR_fore: [
      { t: 0, deg: -3, dx: 0.25, dy: -1 },
      { t: 0.25, deg: -3.5, dx: -0.5, dy: 1 },
      { t: 0.625, deg: -2.5, dx: -0.25, dy: -0.25 },
      { t: 0.75, deg: 10.5, dx: 0.5, dy: 1.25 },
      { t: 0.875, deg: 8.5, dx: 0.75, dy: -0.5 },
      { t: 1, deg: -3, dx: 0.25, dy: -1 },
    ],
  },
};

export const CLIP_WALK_UP: Clip = {
  name: 'walk',
  frames: 9,
  tracks: {
    trunk: [
      { t: 0, deg: 0, dx: 1, dy: 0.25 },
      { t: 0.25, deg: 0, dx: 0, dy: -0.25 },
      { t: 0.625, deg: 0, dx: 0.75, dy: 0.25 },
      { t: 0.75, deg: 0, dx: 1, dy: -0.5 },
      { t: 1, deg: 0, dx: 1, dy: 0.25 },
    ],
    head: [
      { t: 0, deg: 0, dx: 0 },
      { t: 0.25, deg: 0, dx: -0.5 },
      { t: 1, deg: 0, dx: 0 },
    ],
    armL_up: [
      { t: 0, deg: -3.5, dx: 0.25, dy: 0.25 },
      { t: 0.5, deg: 4, dx: -0.25, dy: -0.25 },
      { t: 0.875, deg: 1, dx: 0.25, dy: 0 },
      { t: 1, deg: -3.5, dx: 0.25, dy: 0.25 },
    ],
    armL_fore: [
      { t: 0, deg: 10.5, dx: 0.25, dy: -0.75 },
      { t: 0.125, deg: 9, dx: 0.25, dy: -0.25 },
      { t: 0.375, deg: -17.5, dx: -0.25, dy: 0.5 },
      { t: 0.5, deg: -21, dx: -0.25, dy: 0.5 },
      { t: 0.75, deg: 6, dx: 0, dy: 0.25 },
      { t: 1, deg: 10.5, dx: 0.25, dy: -0.75 },
    ],
    armR_up: [
      { t: 0, deg: -2, dx: 0.25, dy: -0.25 },
      { t: 0.625, deg: 4, dx: 0, dy: 0.5 },
      { t: 1, deg: -2, dx: 0.25, dy: -0.25 },
    ],
    armR_fore: [
      { t: 0, deg: 13.5, dx: 0, dy: 0.25 },
      { t: 0.125, deg: 8.5, dx: 0, dy: 0.5 },
      { t: 0.25, deg: -5.5, dx: 0, dy: 0.25 },
      { t: 0.5, deg: -15, dx: -0.25, dy: -0.75 },
      { t: 0.625, deg: -13, dx: -0.25, dy: -0.5 },
      { t: 0.75, deg: -3.5, dx: 0, dy: 0 },
      { t: 0.875, deg: 9, dx: 0, dy: 0.25 },
      { t: 1, deg: 13.5, dx: 0, dy: 0.25 },
    ],
    legL_up: [
      { t: 0, deg: 2, dx: 0.5, dy: 0.5 },
      { t: 0.25, deg: -3.5, dx: -0.25, dy: -0.5 },
      { t: 0.5, deg: -4.5, dx: -0.75, dy: -0.5 },
      { t: 0.625, deg: -2, dx: -0.25, dy: -0.25 },
      { t: 0.75, deg: 4.5, dx: 0.25, dy: 0.25 },
      { t: 0.875, deg: 6.5, dx: 0.25, dy: 0.25 },
      { t: 1, deg: 2, dx: 0.5, dy: 0.5 },
    ],
    legL_fore: [
      { t: 0, deg: 3, dx: -0.25, dy: -1 },
      { t: 0.25, deg: 3.5, dx: 0.5, dy: 1 },
      { t: 0.625, deg: 2.5, dx: 0.25, dy: -0.25 },
      { t: 0.75, deg: -10.5, dx: -0.5, dy: 1.25 },
      { t: 0.875, deg: -8.5, dx: -0.75, dy: -0.5 },
      { t: 1, deg: 3, dx: -0.25, dy: -1 },
    ],
    legR_up: [
      { t: 0, deg: 4, dx: 0.5, dy: -0.25 },
      { t: 0.25, deg: -5, dx: -0.25, dy: 0.25 },
      { t: 0.5, deg: -3, dx: -0.75, dy: 0.5 },
      { t: 0.625, deg: 0, dx: -0.25, dy: 0.25 },
      { t: 1, deg: 4, dx: 0.5, dy: -0.25 },
    ],
    legR_fore: [
      { t: 0, deg: -1.5, dx: -0.5, dy: 0.25 },
      { t: 0.125, deg: -1.5, dx: 0, dy: -0.75 },
      { t: 0.25, deg: 4, dx: 0.5, dy: 1 },
      { t: 0.375, deg: 3.5, dx: 0.5, dy: -0.75 },
      { t: 0.5, deg: 0.5, dx: 0.5, dy: -1 },
      { t: 0.75, deg: -0.5, dx: -0.25, dy: 1 },
      { t: 1, deg: -1.5, dx: -0.5, dy: 0.25 },
    ],
  },
};

export const CLIP_WALK_LEFT: Clip = {
  name: 'walk',
  frames: 9,
  tracks: {
    trunk: [
      { t: 0, deg: 0, dx: 20, dy: 0.25 },
      { t: 0.125, deg: 0, dx: 22, dy: 0.25 },
      { t: 0.25, deg: 0, dx: 21, dy: -0.25 },
      { t: 0.5, deg: 0, dx: 22.25, dy: 0.25 },
      { t: 0.625, deg: 0, dx: 20, dy: 0.25 },
      { t: 0.75, deg: 0, dx: 19.5, dy: -0.5 },
      { t: 0.875, deg: 0, dx: 19.25, dy: 0 },
      { t: 1, deg: 0, dx: 20, dy: 0.25 },
    ],
    head: [
      { t: 0, deg: -0.5, dx: -0.25 },
      { t: 0.375, deg: -2, dx: -0.25 },
      { t: 0.625, deg: 1, dx: 0.25 },
      { t: 1, deg: -0.5, dx: -0.25 },
    ],
    armNear_up: [
      { t: 0, deg: -15, dx: 0, dy: 0.25 },
      { t: 0.125, deg: -5, dx: 0.25, dy: 0.5 },
      { t: 0.25, deg: 5, dx: -0.25, dy: 0.25 },
      { t: 0.375, deg: 15.5, dx: -0.75, dy: 0 },
      { t: 0.5, deg: 17.5, dx: -0.75, dy: -0.25 },
      { t: 0.625, deg: 7.5, dx: -0.5, dy: -0.5 },
      { t: 0.75, deg: -1.5, dx: 0, dy: -0.25 },
      { t: 0.875, deg: -12, dx: 0.25, dy: 0 },
      { t: 1, deg: -15, dx: 0, dy: 0.25 },
    ],
    armNear_fore: [
      { t: 0, deg: -10, dx: 0.5, dy: 0.25 },
      { t: 0.125, deg: -10, dx: 0.25, dy: 0.25 },
      { t: 0.25, deg: 7, dx: -0.25, dy: 0.25 },
      { t: 0.375, deg: 14.5, dx: -0.5, dy: 0.25 },
      { t: 0.5, deg: 15.5, dx: -0.75, dy: 0.25 },
      { t: 0.625, deg: 6, dx: -0.25, dy: 0.25 },
      { t: 0.75, deg: -10, dx: 0, dy: 0.25 },
      { t: 1, deg: -10, dx: 0.5, dy: 0.25 },
    ],
    armFar_up: [
      { t: 0, deg: 15.5, dx: -0.5, dy: -0.25 },
      { t: 0.125, deg: 6, dx: -0.25, dy: -0.5 },
      { t: 0.375, deg: -15.5, dx: 0.25, dy: 0 },
      { t: 0.5, deg: -17.5, dx: 0.5, dy: 0.25 },
      { t: 0.625, deg: -10, dx: 1, dy: 0.5 },
      { t: 0.75, deg: 0, dx: 0.25, dy: 0.25 },
      { t: 0.875, deg: 11, dx: -0.5, dy: 0 },
      { t: 1, deg: 15.5, dx: -0.5, dy: -0.25 },
    ],
    armFar_fore: [
      { t: 0, deg: 7.5, dx: -0.5, dy: 0.5 },
      { t: 0.125, deg: 7, dx: -0.25, dy: 0.25 },
      { t: 0.25, deg: -6.5, dx: 0.25, dy: 0.25 },
      { t: 0.375, deg: -5, dx: 0.5, dy: 0 },
      { t: 0.5, deg: -8.5, dx: 0.5, dy: 0 },
      { t: 0.625, deg: -8, dx: 0.25, dy: 0 },
      { t: 0.75, deg: 1.5, dx: 0, dy: 0.25 },
      { t: 1, deg: 7.5, dx: -0.5, dy: 0.5 },
    ],
    legNear_up: [
      { t: 0, deg: 24, dx: 0, dy: 0.5 },
      { t: 0.125, deg: 17.5, dx: -0.25, dy: 0.25 },
      { t: 0.25, deg: -1.5, dx: -0.25, dy: -0.5 },
      { t: 0.375, deg: -13, dx: 0, dy: -0.5 },
      { t: 0.5, deg: -30.5, dx: 0.25, dy: -0.5 },
      { t: 0.625, deg: -37.5, dx: 0.25, dy: -0.25 },
      { t: 0.75, deg: -3.5, dx: 0, dy: 0.25 },
      { t: 0.875, deg: 19.5, dx: 0, dy: 0.25 },
      { t: 1, deg: 24, dx: 0, dy: 0.5 },
    ],
    legNear_fore: [
      { t: 0, deg: -3, dx: -3, dy: 0.5 },
      { t: 0.125, deg: -9.5, dx: -2.75, dy: 0.75 },
      { t: 0.25, deg: 8, dx: 0, dy: 1 },
      { t: 0.375, deg: 15.5, dx: 1.75, dy: 1.75 },
      { t: 0.5, deg: 30, dx: 2.25, dy: 2 },
      { t: 0.625, deg: 23.5, dx: 2.25, dy: 2 },
      { t: 0.75, deg: -34.5, dx: 0.5, dy: 1.25 },
      { t: 0.875, deg: -28.5, dx: -3, dy: 0.75 },
      { t: 1, deg: -3, dx: -3, dy: 0.5 },
    ],
    legFar_up: [
      { t: 0, deg: -23.5, dx: 0.25, dy: -0.25 },
      { t: 0.125, deg: -34, dx: 0.25, dy: 0 },
      { t: 0.25, deg: 8.5, dx: 0, dy: 0.25 },
      { t: 0.375, deg: 28, dx: -0.25, dy: 0.25 },
      { t: 0.5, deg: 29.5, dx: 0, dy: 0.5 },
      { t: 0.625, deg: 23, dx: 0, dy: 0.25 },
      { t: 0.75, deg: 3, dx: -0.25, dy: -0.25 },
      { t: 0.875, deg: -11, dx: 0, dy: -0.25 },
      { t: 1, deg: -23.5, dx: 0.25, dy: -0.25 },
    ],
    legFar_fore: [
      { t: 0, deg: 23, dx: 2.25, dy: 2 },
      { t: 0.125, deg: 23, dx: 2.25, dy: 2 },
      { t: 0.25, deg: -45.5, dx: -1.25, dy: 0.75 },
      { t: 0.375, deg: -33, dx: -3, dy: 0.5 },
      { t: 0.5, deg: -3.5, dx: -3, dy: 0.5 },
      { t: 0.625, deg: -10.5, dx: -3, dy: 0.5 },
      { t: 0.75, deg: 8, dx: -0.5, dy: 0.75 },
      { t: 1, deg: 23, dx: 2.25, dy: 2 },
    ],
  },
};

/** The three AUTHORED facings; east is west mirrored at bake time (`facing.ts`). */
export const CLIP_WALK: Readonly<Record<'down' | 'up' | 'left', Clip>> = {
  down: CLIP_WALK_DOWN,
  up: CLIP_WALK_UP,
  left: CLIP_WALK_LEFT,
};
