/**
 * GENERATED by `npx tsx scripts/motion-import-bvh.ts wave` — do not
 * hand-edit; re-run to change. Byte-identity is pinned by
 * `tests/unit/motion-import-determinism.test.ts`.
 *
 * Capture: vendor/mocap/cmu/141_16.bvh — CMU Graphics Lab Motion Capture
 * Database, cgspeed BVH conversion, 120 fps (see CREDITS.md).
 *
 * wave hello — a ONE-SHOT, not a loop. Range is the whole gesture: arm hanging
 * at frame 1, up by ~35, waving until ~200, down and settled by ~240.
 * Reference frame 0 is therefore the actor STANDING (the range start), which
 * is what the rig rest cell should mean. Phase budget at 17 frames: one frame
 * of raise, ~13 held aloft, two of lowering — the raise genuinely takes 0.13 s
 * in the capture, so more frames buy a smoother hold, not a smoother raise.
 * CAVEAT, STATED RATHER THAN HIDDEN: the wave proper is a 24-frame forearm
 * oscillation and this decimation samples every ~15.6 frames, so what survives
 * on the forearm chips is an UNDER-SAMPLED oscillation — right limb, right
 * amplitude (~±25 deg), right duration, wrong phase. That is the honest trade
 * at a sprite-row frame count; resolving 24 frames would need ~60 baked
 * frames. The dangerous failure (the unwrapper picking the wrong branch and
 * winding the chip past a full turn) was checked for and does not happen HERE:
 * the worst per-frame step is 113 deg, and it is the real raise. It DOES
 * happen at 11 frames, where the sample spacing lands near the oscillation
 * period and the forearm winds to -359 deg — which is why the frame count is
 * not a free dial.
 *
 * Options: range [1, 250] · frames 17 ·
 *   referenceFrame 0 ·
 *   loop 'none' · rootMotion 'in-place' (default) ·
 *   pxPerUnit 2.110113 (51 px figure ÷ T-pose extent 24.169 units)
 *
 * Cycle: 249 source frames = 2.075 s.
 * Stride: 0.7 px per cycle — this clip does not travel; ground speed 0.
 * Loop residual (capture, first→last pose): 2.09 px RMS per joint.
 *
 * Per facing — tracks, worst per-frame angle step, t=0..t=1 gap, plants,
 * and the foreshortening floor (least of any rotating bone in-plane length):
 *   down  10 tracks · max  153.5° · step   113° (armL_fore) · loop 9° · 0 plant(s) · in-plane ≥ 0.69 (armL_fore)
 *   up    10 tracks · max  153.5° · step   113° (armR_fore) · loop 9° · 0 plant(s) · in-plane ≥ 0.69 (armR_fore)
 *   left  10 tracks · max    102° · step    54° (armFar_fore) · loop 9° · 0 plant(s) · in-plane ≥ 0.27 (armFar_up)
 *
 * A per-frame step approaching 180° would mean the gesture outran the baked
 * rate and the angle unwrapper picked the wrong branch. A foreshortening
 * floor approaching 0 would mean a bone points at the camera and the rig is
 * rotating a chip on noise. Neither happens here — the captures that DID
 * fail those two reads are listed, with their numbers, in the importer.
 */

import type { Clip } from '../rig';

export const CLIP_WAVE_DOWN: Clip = {
  name: 'wave',
  frames: 17,
  tracks: {
    trunk: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.125, deg: 0, dx: 3, dy: -0.5 },
      { t: 0.1875, deg: 0, dx: 5, dy: -0.75 },
      { t: 0.3125, deg: 0, dx: 7.25, dy: -0.5 },
      { t: 0.5, deg: 0, dx: 6.5, dy: -0.5 },
      { t: 0.625, deg: 0, dx: 4.75, dy: -0.5 },
      { t: 0.8125, deg: 0, dx: 0.5, dy: 0 },
      { t: 1, deg: 0, dx: 0, dy: 0 },
    ],
    head: [
      { t: 0, deg: 0, dx: 0 },
      { t: 0.1875, deg: 0, dx: 0.75 },
      { t: 0.625, deg: 0, dx: 1.75 },
      { t: 1, deg: 0, dx: -0.5 },
    ],
    armL_up: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.0625, deg: 21, dx: 0.25, dy: -0.25 },
      { t: 0.125, deg: 67, dx: 0.75, dy: -0.5 },
      { t: 0.1875, deg: 71, dx: 1, dy: -0.75 },
      { t: 0.375, deg: 66.5, dx: 1.25, dy: -1 },
      { t: 0.4375, deg: 58.5, dx: 1.25, dy: -0.75 },
      { t: 0.6875, deg: 60, dx: 1.25, dy: -0.75 },
      { t: 0.75, deg: 49.5, dx: 1.25, dy: -0.75 },
      { t: 0.8125, deg: 18.5, dx: 1, dy: -0.5 },
      { t: 0.875, deg: 2.5, dx: 0, dy: -0.25 },
      { t: 0.9375, deg: -6.5, dx: -0.5, dy: 0.25 },
      { t: 1, deg: -4, dx: -0.25, dy: 0.25 },
    ],
    armL_fore: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.0625, deg: 113, dx: 0, dy: 1 },
      { t: 0.25, deg: 106, dx: 1.25, dy: 2.75 },
      { t: 0.375, deg: 127.5, dx: 0.75, dy: 3 },
      { t: 0.4375, deg: 112.5, dx: 1, dy: 2.75 },
      { t: 0.5625, deg: 131, dx: 0.75, dy: 3 },
      { t: 0.625, deg: 116.5, dx: 1, dy: 2.75 },
      { t: 0.6875, deg: 153.5, dx: 0.75, dy: 3 },
      { t: 0.75, deg: 93, dx: 0.75, dy: 3 },
      { t: 0.8125, deg: 61.5, dx: -0.25, dy: 1.5 },
      { t: 0.875, deg: 3.5, dx: 0, dy: 0.25 },
      { t: 1, deg: 7.5, dx: 0, dy: -0.25 },
    ],
    armR_up: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.125, deg: 6.5, dx: 0.75, dy: 0.5 },
      { t: 0.4375, deg: 5, dx: 1.25, dy: 0.75 },
      { t: 0.625, deg: 9, dx: 1.5, dy: 1 },
      { t: 0.8125, deg: 6.5, dx: 1, dy: 0.5 },
      { t: 0.875, deg: 0, dx: 0, dy: 0 },
      { t: 1, deg: -1.5, dx: -0.5, dy: -0.25 },
    ],
    armR_fore: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.1875, deg: -4, dx: -0.25, dy: -0.25 },
      { t: 0.5625, deg: -1, dx: -0.25, dy: -0.5 },
      { t: 0.625, deg: -4, dx: -0.25, dy: -0.5 },
      { t: 0.75, deg: -3.5, dx: -0.25, dy: -0.5 },
      { t: 1, deg: 9, dx: 0, dy: 0.25 },
    ],
    legL_up: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.125, deg: 4.5, dx: -0.25, dy: 0 },
      { t: 0.1875, deg: 10.5, dx: 0, dy: 0.25 },
      { t: 0.25, deg: 14, dx: 0, dy: 0.5 },
      { t: 0.375, deg: 16.5, dx: 0, dy: 0.5 },
      { t: 0.625, deg: 12, dx: 0.25, dy: 0.25 },
      { t: 0.8125, deg: -0.5, dx: 0, dy: -0.25 },
      { t: 1, deg: -2, dx: -0.25, dy: 0 },
    ],
    legL_fore: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.375, deg: 7, dx: -2, dy: 1.5 },
      { t: 0.625, deg: 7.5, dx: -1.5, dy: 1 },
      { t: 0.75, deg: 0, dx: -0.5, dy: -0.25 },
      { t: 1, deg: 0, dx: 0.25, dy: 0 },
    ],
    legR_up: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.1875, deg: 15.5, dx: 0, dy: -0.5 },
      { t: 0.375, deg: 20, dx: 0, dy: -0.75 },
      { t: 0.625, deg: 13.5, dx: 0.25, dy: -0.5 },
      { t: 0.75, deg: 6, dx: 0, dy: 0 },
      { t: 0.875, deg: 1.5, dx: -0.25, dy: 0 },
      { t: 1, deg: 1.5, dx: -0.5, dy: 0 },
    ],
    legR_fore: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.0625, deg: -5.5, dx: -0.75, dy: -0.5 },
      { t: 0.1875, deg: 1, dx: -2, dy: 0.5 },
      { t: 0.375, deg: 6.5, dx: -2.5, dy: 0.75 },
      { t: 0.6875, deg: 6, dx: -1.25, dy: 0.25 },
      { t: 0.8125, deg: -3.5, dx: -0.5, dy: 0 },
      { t: 1, deg: -3.5, dx: -0.25, dy: 0 },
    ],
  },
};

export const CLIP_WAVE_UP: Clip = {
  name: 'wave',
  frames: 17,
  tracks: {
    trunk: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.125, deg: 0, dx: -3, dy: -0.5 },
      { t: 0.1875, deg: 0, dx: -5, dy: -0.75 },
      { t: 0.3125, deg: 0, dx: -7.25, dy: -0.5 },
      { t: 0.5, deg: 0, dx: -6.25, dy: -0.5 },
      { t: 0.625, deg: 0, dx: -4.5, dy: -0.5 },
      { t: 0.8125, deg: 0, dx: -0.5, dy: 0 },
      { t: 1, deg: 0, dx: 0, dy: 0 },
    ],
    head: [
      { t: 0, deg: 0, dx: 0 },
      { t: 0.1875, deg: 0, dx: -0.75 },
      { t: 0.625, deg: 0, dx: -1.75 },
      { t: 1, deg: 0, dx: 0.5 },
    ],
    armL_up: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.125, deg: -6.5, dx: -0.75, dy: 0.5 },
      { t: 0.4375, deg: -5, dx: -1.25, dy: 0.75 },
      { t: 0.625, deg: -9, dx: -1.5, dy: 1 },
      { t: 0.8125, deg: -6.5, dx: -1, dy: 0.5 },
      { t: 0.875, deg: 0, dx: 0, dy: 0 },
      { t: 1, deg: 1.5, dx: 0.5, dy: -0.25 },
    ],
    armL_fore: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.1875, deg: 4, dx: 0.25, dy: -0.5 },
      { t: 0.5625, deg: 1, dx: 0.25, dy: -0.75 },
      { t: 0.625, deg: 4, dx: 0.25, dy: -0.75 },
      { t: 0.75, deg: 3.5, dx: 0.25, dy: -0.75 },
      { t: 1, deg: -9, dx: 0, dy: 0.25 },
    ],
    armR_up: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.0625, deg: -21, dx: -0.25, dy: -0.25 },
      { t: 0.125, deg: -67, dx: -0.75, dy: -0.5 },
      { t: 0.1875, deg: -71, dx: -1, dy: -0.75 },
      { t: 0.375, deg: -66.5, dx: -1.25, dy: -1 },
      { t: 0.4375, deg: -58.5, dx: -1.25, dy: -0.75 },
      { t: 0.6875, deg: -60, dx: -1.25, dy: -0.75 },
      { t: 0.75, deg: -49.5, dx: -1.25, dy: -0.75 },
      { t: 0.8125, deg: -18.5, dx: -1, dy: -0.5 },
      { t: 0.875, deg: -2.5, dx: 0, dy: -0.25 },
      { t: 0.9375, deg: 6.5, dx: 0.5, dy: 0.25 },
      { t: 1, deg: 4, dx: 0.25, dy: 0.25 },
    ],
    armR_fore: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.0625, deg: -113, dx: 0.25, dy: 0.25 },
      { t: 0.25, deg: -106, dx: -0.25, dy: 1.75 },
      { t: 0.375, deg: -127.5, dx: 0, dy: 2.5 },
      { t: 0.4375, deg: -112.5, dx: 0, dy: 1.5 },
      { t: 0.5625, deg: -131, dx: 0, dy: 1.75 },
      { t: 0.625, deg: -116.5, dx: 0, dy: 1.5 },
      { t: 0.6875, deg: -153.5, dx: 0, dy: 2.25 },
      { t: 0.75, deg: -93, dx: 0, dy: 1.25 },
      { t: 0.8125, deg: -61.5, dx: 0.5, dy: 1 },
      { t: 0.875, deg: -3.5, dx: 0, dy: 0 },
      { t: 1, deg: -7.5, dx: 0, dy: -0.25 },
    ],
    legL_up: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.1875, deg: -15.5, dx: 0, dy: -0.5 },
      { t: 0.375, deg: -20, dx: 0, dy: -0.75 },
      { t: 0.625, deg: -13.5, dx: -0.25, dy: -0.5 },
      { t: 0.75, deg: -6, dx: 0, dy: 0 },
      { t: 0.875, deg: -1.5, dx: 0.25, dy: 0 },
      { t: 1, deg: -1.5, dx: 0.5, dy: 0 },
    ],
    legL_fore: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.0625, deg: 5.5, dx: 0.75, dy: -0.5 },
      { t: 0.1875, deg: -1, dx: 2, dy: 0.5 },
      { t: 0.375, deg: -6.5, dx: 2.5, dy: 0.75 },
      { t: 0.6875, deg: -6, dx: 1.25, dy: 0.25 },
      { t: 0.8125, deg: 3.5, dx: 0.5, dy: 0 },
      { t: 1, deg: 3.5, dx: 0.25, dy: 0 },
    ],
    legR_up: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.125, deg: -4.5, dx: 0.25, dy: 0 },
      { t: 0.1875, deg: -10.5, dx: 0, dy: 0.25 },
      { t: 0.25, deg: -14, dx: 0, dy: 0.5 },
      { t: 0.375, deg: -16.5, dx: 0, dy: 0.5 },
      { t: 0.625, deg: -12, dx: -0.25, dy: 0.25 },
      { t: 0.8125, deg: 0.5, dx: 0, dy: -0.25 },
      { t: 1, deg: 2, dx: 0.25, dy: 0 },
    ],
    legR_fore: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.375, deg: -7, dx: 2, dy: 1.5 },
      { t: 0.625, deg: -7.5, dx: 1.5, dy: 1 },
      { t: 0.75, deg: 0, dx: 0.5, dy: -0.25 },
      { t: 1, deg: 0, dx: -0.25, dy: 0 },
    ],
  },
};

export const CLIP_WAVE_LEFT: Clip = {
  name: 'wave',
  frames: 17,
  tracks: {
    trunk: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.0625, deg: 0, dx: 1.25, dy: 0 },
      { t: 0.125, deg: 0, dx: -1, dy: -0.5 },
      { t: 0.1875, deg: 0, dx: -3.5, dy: -0.75 },
      { t: 0.25, deg: 0, dx: -4.5, dy: -0.5 },
      { t: 0.5625, deg: 0, dx: -5, dy: -0.5 },
      { t: 0.6875, deg: 0, dx: -4.5, dy: -0.5 },
      { t: 0.75, deg: 0, dx: -2, dy: -0.5 },
      { t: 0.8125, deg: 0, dx: -0.5, dy: 0 },
      { t: 1, deg: 0, dx: 0, dy: 0 },
    ],
    head: [
      { t: 0, deg: 0, dx: 0 },
      { t: 0.0625, deg: -2, dx: 0.25 },
      { t: 0.1875, deg: 2, dx: 1.25 },
      { t: 0.4375, deg: 0.5, dx: 0.75 },
      { t: 0.625, deg: -4, dx: 0.75 },
      { t: 1, deg: 2.5, dx: 0.75 },
    ],
    armNear_up: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.1875, deg: 3.5, dx: 0.5, dy: 0.5 },
      { t: 0.5, deg: 0, dx: -0.5, dy: 0.75 },
      { t: 0.625, deg: 2.5, dx: 0.5, dy: 1 },
      { t: 0.8125, deg: 2, dx: 0.5, dy: 0.5 },
      { t: 1, deg: 7.5, dx: -0.5, dy: -0.25 },
    ],
    armNear_fore: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.125, deg: -2.5, dx: 0, dy: 0 },
      { t: 0.1875, deg: 1.5, dx: 0, dy: 0.25 },
      { t: 0.4375, deg: -1.5, dx: 0, dy: 0 },
      { t: 0.5, deg: 2, dx: 0, dy: 0 },
      { t: 0.6875, deg: -3, dx: 0, dy: 0.25 },
      { t: 0.75, deg: 0.5, dx: 0, dy: 0.25 },
      { t: 0.8125, deg: -4.5, dx: 0, dy: 0 },
      { t: 0.9375, deg: 3, dx: -0.25, dy: 0 },
      { t: 1, deg: 0.5, dx: -0.25, dy: 0 },
    ],
    armFar_up: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.0625, deg: 40.5, dx: 0.75, dy: -0.25 },
      { t: 0.125, deg: 93, dx: 1.5, dy: -0.5 },
      { t: 0.1875, deg: 102, dx: 1.75, dy: -0.75 },
      { t: 0.25, deg: 92, dx: 1.75, dy: -1 },
      { t: 0.4375, deg: 80.5, dx: 1.75, dy: -0.75 },
      { t: 0.5, deg: 67.5, dx: 1.25, dy: -0.75 },
      { t: 0.625, deg: 78, dx: 1.25, dy: -1 },
      { t: 0.75, deg: 66, dx: 1.25, dy: -0.75 },
      { t: 0.8125, deg: 14, dx: 1.25, dy: -0.5 },
      { t: 0.875, deg: -1, dx: 1.75, dy: -0.25 },
      { t: 1, deg: -0.5, dx: 2, dy: 0.25 },
    ],
    armFar_fore: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.0625, deg: 54, dx: -0.75, dy: 0.25 },
      { t: 0.125, deg: 8, dx: -0.5, dy: -1.5 },
      { t: 0.1875, deg: -1, dx: -0.25, dy: -1.5 },
      { t: 0.25, deg: 42, dx: -0.5, dy: -0.75 },
      { t: 0.375, deg: 16.5, dx: -0.75, dy: -2.5 },
      { t: 0.4375, deg: 57, dx: -0.75, dy: -1 },
      { t: 0.625, deg: 53.5, dx: -0.75, dy: -0.75 },
      { t: 0.6875, deg: 19, dx: -1.25, dy: -2.5 },
      { t: 0.75, deg: 68, dx: -1, dy: -1 },
      { t: 0.875, deg: -1.5, dx: 0, dy: -0.25 },
      { t: 1, deg: -9, dx: 0, dy: 0.25 },
    ],
    legNear_up: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.0625, deg: 9, dx: -0.25, dy: 0 },
      { t: 0.1875, deg: -13.5, dx: -0.75, dy: -0.5 },
      { t: 0.25, deg: -18, dx: -0.75, dy: -0.5 },
      { t: 0.375, deg: -20, dx: -1, dy: -0.75 },
      { t: 0.6875, deg: -15, dx: 0, dy: -0.25 },
      { t: 0.75, deg: -4, dx: 0, dy: 0 },
      { t: 0.8125, deg: 2, dx: -0.25, dy: 0 },
      { t: 0.9375, deg: 0, dx: -1, dy: -0.25 },
      { t: 1, deg: 2, dx: -1, dy: 0 },
    ],
    legNear_fore: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.0625, deg: -18, dx: -1.25, dy: -0.25 },
      { t: 0.1875, deg: 2.5, dx: 2, dy: 0.75 },
      { t: 0.3125, deg: 9.5, dx: 2.75, dy: 1 },
      { t: 0.6875, deg: 9, dx: 2.25, dy: 1 },
      { t: 0.8125, deg: -7, dx: -0.25, dy: 0 },
      { t: 0.9375, deg: -2.5, dx: 0, dy: 0 },
      { t: 1, deg: -5, dx: -0.25, dy: 0 },
    ],
    legFar_up: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.125, deg: -4, dx: 0.25, dy: 0 },
      { t: 0.375, deg: 1, dx: 0.75, dy: 0.5 },
      { t: 0.625, deg: 2.5, dx: -0.25, dy: 0.25 },
      { t: 0.75, deg: -4.5, dx: -0.25, dy: 0 },
      { t: 1, deg: 1.5, dx: 0.75, dy: 0 },
    ],
    legFar_fore: [
      { t: 0, deg: 0, dx: 0, dy: 0 },
      { t: 0.125, deg: -2, dx: 0.75, dy: 0 },
      { t: 0.3125, deg: -8.5, dx: 0, dy: 0.25 },
      { t: 0.5625, deg: -8, dx: 0, dy: 0.25 },
      { t: 0.625, deg: -10.5, dx: -0.25, dy: 0.25 },
      { t: 0.75, deg: -0.5, dx: 0.75, dy: 0 },
      { t: 1, deg: 0, dx: -0.25, dy: 0 },
    ],
  },
};

/** The three AUTHORED facings; east is west mirrored at bake time (`facing.ts`). */
export const CLIP_WAVE: Readonly<Record<'down' | 'up' | 'left', Clip>> = {
  down: CLIP_WAVE_DOWN,
  up: CLIP_WAVE_UP,
  left: CLIP_WAVE_LEFT,
};
