// src/core/content-version.ts
// Single source of truth for the two manually-bumped cache-busting versions.
// Bump a constant when you make a change you want reflected in-game without the
// player having to clear storage or hit "New World".

/**
 * Bump when building/asset GENERATION changes (geometry, metric scale, blueprint
 * output). A baked sprite whose `recipeVersion` differs from this is treated as
 * STALE and skipped, so the live parametric generator renders instead.
 * Regenerate the base library at the new version to let baked art win again.
 * History: 'v2' retired the 'v1' baked art left metrically wrong by the
 * metric-scale standardization; 'v3' was the chroma-key sprite pipeline
 * (magenta-background img2img + keyed alpha); 'v4' changes the CACHED FORMAT —
 * the stored blob is now the processed sprite (keyed + registered to the
 * geometry mask + quantized, at final resolution) rather than the raw LLM PNG,
 * with validation gating what gets persisted at all; 'v5' is the adaptive
 * pipeline — negotiation-band registration, detail-inviting prompts, relaxed
 * IoU gate, and the rebuilt castle_keep + window features on tall presets;
 * 'v6' is the medieval detail pass — material-driven eaves/verges, half-hip
 * (gablet) roofs, dormers, ridge louvres, slimmer multi-chimneys, per-type
 * window programmes, rectangular plans (see
 * docs/reference/medieval-building-reference.md); 'v7' deepens the eaves —
 * material overhangs grown to real medieval depths (thatch 60 cm … slate
 * 20 cm) with sprocketed-eave drop capping so door heads stay clear;
 * 'v8' is the roof-slab remodel — roofs are individual sloped boards with real
 * thickness (projecting eaves AND verges read as boards, not a solid wedge) plus
 * recessed gable-end tympana, and masonry/metal ridge stacks are offset BESIDE
 * the ridge beam (timber smoke-louvres still straddle it) so chimneys no longer
 * pierce the structural ridge;
 * 'v9' — connectome Slice 1: a building's smoke vent is now DERIVED from its hearth
 * (early-medieval commoner dwellings — cottage/longhouse/yurt — get a period-correct
 * ridge louver, NOT a chimney; vents stripped from their presets and re-derived), so
 * cottage/longhouse/yurt geometry shifts;
 * 'v10' — generative openings: doors + windows are now DERIVED from the room graph
 * (exterior portals ⇒ doors, needs-light zones ⇒ windows, distributed by wall length +
 * era glazing) for presets tagged 'gen-openings' (cottage/shrine/guard_post/watermill/
 * temple_small migrated to fact-seeds), so their fenestration shifts.
 * 'v11' — procedural weathering: building/prop albedo is aged in `composeStructure`
 * (dirt pooling low, grime in AO crevices, vertical rain-streaks, rust blooming on
 * metal) via `src/assetgen/render/weathering.ts`; pure flora/rock left pristine.
 * 'v12' — lit windows: window panes are a new 'glass' material (dark cool albedo by
 * day) carrying a warm emissive, so the renderer glows them at night (emissive ×
 * nightFactor). Shifts the grey/material/emissive of any preset with windows.
 * 'v13' — real flora generators: trees/shrubs now grow recursive proctree branch
 * skeletons (broadleaf/weeping) or space-colonization crowns (conifer cones) keyed
 * on a per-species crownShape, replacing the six L-system recipes that collapsed all
 * species to ~3 silhouettes. Shifts the geometry of every `branch_plant` (plant) sprite.
 * 'v14' — layered-connectome Layer 1 (STRUCTURE): a building's frameType is now selected
 * from its wall material + era/region and GATES its form — a solid/cruck/stave wall can no
 * longer jetty (only a box-frame does), and storeys are capped to what the frame bears. So
 * any building whose authored massing exceeded its frame shifts (e.g. the stone manor's
 * cross-wing loses its timber-frame jetty). See the layered-connectome-expression spec.
 * 'v15' — layered-connectome Layer 2a (FORM): a `gen-form` body's vertical massing
 * (plan/levels/jetty/storeyM) is now DERIVED from the program + structure rather than
 * hand-listed — a box-frame dwelling stacks a jettied upper storey, a cruck one stays a
 * single low range. Migrated the dwelling family (cottage/tavern/townhouse); the cottage's
 * derived form matches its authored one, the box-frame inns/townhouses take the frame's
 * full jetty. Footprint held (placement unchanged). Shifts the box-frame dwellings' geometry.
 * 'v16' — layered-connectome Layer 3a (FABRIC): STRUCTURE now gates fabric. (1) The frame's
 * fenestration policy drives derived openings — a mass wall takes few, widely-spaced lights,
 * a box frame's panels glaze generously — so any `gen-openings` body's window count/spacing
 * shifts to the frame's rhythm (the cruck cottage loses a window; mass-wall buildings grow
 * austere). (2) A masonry wall-chimney requires a flue-capable frame: a cruck/stave build
 * can never grow a stone stack and keeps its ridge smokehole however late/rich. Footprint
 * held (placement unchanged). See the layered-connectome-expression spec.
 * 'v17' — layered-connectome Layer 2b (FORM footprint variety): a `gen-form` body's plan
 * LENGTH is now sized to a bay count picked from the program's `sizeBays` range by the
 * per-instance seed (a cottage is 1–2 bays, a tavern 2–3), CLAMPED to the authored footprint
 * so the lot — and placement — is unchanged. Two cottages on a street now read as a short
 * single-bay cot and a longer two-bay one rather than clones. The name-derived default
 * cottage resolves to a shorter single-bay body, so its geometry shifts (see
 * assetgen-golden). Pairs with the placer threading a per-instance seed (a WORLD bump, since
 * the generative catalogue→geometry bridge grows the FOOTPRINT itself per instance).
 * 'v18' — layered-connectome Layer 3b (bay-aware openings): a `gen-openings` body's WINDOWS now
 * snap to the structural bay CENTRES — the frame's `bayModule` (metres/bay) divides the wall run
 * into panels and a window lights one panel each (skipping the door's bay), instead of the old
 * fixed fractional slots. So fenestration sits where a real timber-frame/masonry wall carries it
 * (panels between posts/piers). Window COUNT is unchanged (still structure-gated by spacing/
 * maxPerFace) — only positions move, so footprint/placement hold. Shifts the pane positions of
 * any structure-annotated `gen-openings` body. See the layered-connectome-expression spec.
 * 'v19' — layered-connectome Layer 3b (undercroft/cellar): a buildingType that declares
 * `undercroft` (the burgage townhouse), built on a masonry-capable frame (mass-wall/box-frame)
 * and stacking ≥2 storeys, now renders its GROUND storey as a STONE base course carrying the
 * (timber) upper — `buildingFacets` splits the wall solid at the base-course height with a
 * Manifold boolean (stone band + wall-material upper). Only undercroft bodies change; every
 * other building's wall is byte-identical (the single-material path is the original code).
 * See the layered-connectome-expression spec.
 * 'v20' — E3 shrine-procession slice 1 (retire temple_small): the hand-tuned `temple_small`
 * preset is gone — a temple now EXPRESSES from its church-axial programme through the fold
 * (generative bridge → FORM → FABRIC), so its geometry is derived not pinned. The generative
 * bridge gains a SACRED-AXIAL footprint rule (a temple/shrine cella is DEEPER than wide, the
 * nave fronting the door with a pediment; an axial barn stays wide). Temples now vary their
 * footprint per instance. See the shrine-procession spec.
 * 'v21' — E3 axis-mundi spire: a WORSHIP building (temple/church/shrine — not a barn, told
 * apart by its single entrance vs the barn's opposed cart doors) now crowns its ridge with a
 * stone STEEPLE — a new `spire` ridge-feature kind (a slender shaft + a pointed conical cap),
 * derived in connectomeToBlueprint. Shifts the geometry of every worship building; dwellings/
 * barns are unchanged. See the shrine-procession spec.
 * 'v22' — E3 threshold stoup (Law 1): a new `stoup` prop (a stone pedestal + bored basin,
 * composed from raw prims — no new part renderer) — the holy-water cleansing basin co-placed
 * at a sacred precinct's border. Additive (a new prop recipe; existing baked art unaffected).
 */
export const ART_RECIPE_VERSION = 'v24';  // ROOF VOCABULARY + ROUND TESSELLATION: gambrel/mansard/saltbox/cross_gable are REAL geometry in `solids.ts` (no longer collapsed to gable/hip — the barn is now gambrel), tympana recess under the slope boards (kills the raking-edge z-fight stipple), and round solids (cylinder/cone/ellipsoid) tessellate by radius (`roundSegments`, chord ≈ 0.12 tiles) instead of the flat 32 — towers/domes/wells stop reading polygonal. Plus ARCHITECTURAL TRIM (`blueprint/parts/trim.ts`): two-stage stepped BUTTRESSES between the windows + braced corners on worship bodies (connectome-derived), and crenellated PARAPETS (breast + merlons, reusing the defensive-wall battlement builders) on flat-roofed towers/keeps. Barn + round buildings + church/tower/keep massing changed ⇒ invalidate cached sprites. (v23 — CHURCH: grounded WEST TOWER + broach spire over the entrance gable, and tall pointed LANCET windows on worship buildings.)

/**
 * Bump when WORLDGEN / preset output changes (footprints, placement, heights).
 * An autosave stamped with a different value is discarded on load → a fresh
 * world is generated. Distinct from SAVE_VERSION (which guards the save *schema*).
 */
export const WORLD_CONTENT_VERSION = 81;  // ROUND 6 — DEFENSIVE STRUCTURES THAT MEAN IT + GROUND-BLEND (five coupled changes, one bump): (1) TERRAIN-SEEKING RING (WP-R): masonry town-wall rays now spend a bounded outward slack to land on locally high ground / the break of slope (`chooseTerrainRadius`, enclosure.ts) — building enclosure stays the hard constraint; every closed ring carries DENSE per-side `segments[i].defends: 'open'|'water'|'steep'` metadata (barrier.ts) + `sealWetBlocking` opens plain gaps over any blocking cell literally in water. Ring paths shift on relief/water-adjacent masonry towns. (2) COVERAGE TOWERS + DITCH + KILLING FIELD (WP-S): towers are a defensive DECISION persisted on `run.towers` (gate flanking pairs > salient corners > fill to MAX_TOWER_SPACING 24t; steep 2×, water unbounded); town walls get a ~1 m dry ditch outside the curtain (shared deformation channel, causeways at every gate, never under buildings/roads/water/farmland) and a ~6-tile killing-field vegetation cull on open legs. (3) BARRIER MASS/JOIN FIXES (WP-U, + ART geometry): ONE readable stair at the main gate (the per-segment rubble stubs are gone), gatehouse towers FRAME the opening + the timber leaf grounds to the sill, corner drums bury square-cut chunk end-faces, merlons phase off GLOBAL path-distance (no seam notch; one shared period incl. towers), towers course like the curtain, and barrier sprites carry an explicit foot anchor so wall/tower bases meet on slopes. (4) GROUND-BLEND (WP-V): every building footprint (burgage lots + civic sites) gets a settle-in pad (mean base −0.12 m, feather 2.5 tiles — grade ramps up to the walls) and the wear prewarm seeds doorstep blobs (door anchors) + perimeter rings on busy buildings through the trample grid. (5) HOSTILE-APPROACH LINT (WP-T): new `defense.closed-circuit` (error) / `defense.gate-observed` / `defense.no-cheap-bypass` contracts evaluate every ring raider's-eye. Discard older autosaves. (Round 5 note kept below.)
//                                          (prev 80) ROUND 5 — ROADS, GATES & DESIRE LINES (three coupled worldgen changes, one bump): (1) GATES-FIRST COMMIT: gates are COMMITTED as portal nodes on the traced ring (one per connection direction, landward, spacing-deduped — `commitDirectionGates`, `world/enclosure.ts`) BEFORE any road or street is carved; interior street connectors grow FROM each gate at layout time (`building-placer.ts`) and approach roads terminate at committed gates by construction, so the two orphan-gate `wireGateToRoad` stitches are demoted to logged degenerate repair (fire 0× on healthy seeds; `ensureMainGate`'s road-scan fallback deleted, its landward guarantee absorbed into the commit pass). Gate positions + interior connectors shift; seed 12345 lint findings drop 32→25 (cleaner, less-parallel roads). (2) TRAMPLE PREWARM: `settlement-wear` is absorbed into the new desire-line trample system (`sim/trample.ts`) as a gen-time PREWARM of the same sparse accumulator grid; worn-dirt lanes shift marginally vs the old threshold pass. At runtime NPC traffic deposits into the grid (3 Hz) and a 0.25 Hz pass promotes/reverts trails with hysteresis (HI 120 / LO 80, ×0.9 decay); trails cap at `dirt` (never road-class); bare `dirt` path cost 0.5→0.8. (3) FILLET RASTER RECONCILIATION: the filleted gate-approach + building-anchor render centerline is re-rasterized into the tile mask (`reconcileFilletRaster`, `road-deformation.ts` — additive-only, hard-blocked on curtain/water-sans-bridge/greens/solids) so the tiles NPCs walk match the smoothed ribbon the player sees. Discard older autosaves. See prior notes below.
//                                          (prev 79) WET-SEAT RECONCILIATION (#22): a building can be placed on validated dry ground and STILL end up on water — the inter-POI connection carve (`buildRoadGraph`) runs AFTER settlements, and a `river`/`wall` feature deliberately ignores building obstacles (a real river doesn't detour around a building), so an authored river reaching for a POI a building already occupies floods part of its footprint after the fact (swamp_shrine's shrine sat on 2 water tiles on genSeed 12345 — `crystal_lake`→`murkmire_swamp`'s river terminates right where the shrine's fallback placement had landed). New pass `reconcileBuildingsWithWater` (`world/building-water-reconcile.ts`) runs once every terrain-mutating carve is done: any building whose footprint now touches water is nudged to the nearest dry, unoccupied, off-road ground (same "final authority" pattern as `reconcileBarriersWithBuildings`). Also fixes a related residual: `orthogonalize`'s diagonal-corner filler could land on water without being registered as a bridge cell, leaving a 1-tile un-bridged gap mid-crossing (road-x-water on genSeed 12345's re8) — the filler is now folded into the edge's `bridgeCells` for a bridging road. `npm run lint:world` reaches 0 errors on both seeds.
//                                          (prev 78) WORLD-COMPILER WP-C junction reconciliation: croft rings now OPEN a real gate where a lane threads them (road-x-barrier fix — `deriveCroftEnclosures` gains a road-gate test, parity with the settlement ring), a wet crossing bank anchor snaps outward to dry land so a bridge deck seats both abutments (bridge.seating), and a non-road (river/wall) graph edge no longer stamps a stray `bridge` tile with no deck over it (bridge.tiles-vs-deck; `bridgeCells` is now road-only). Croft gate spans + one re-seated deck + one un-stamped river-bridge tile change worldgen output ⇒ discard older autosaves. See prior notes below.
//                                          (prev 77) TERRAIN-FEATURE FIX EPIC (rivers first): the river CARVE + render network now classify against the SAME styled flow threshold as the tile raster (`styledRiverFlowThreshold` — was a fixed 560, which on real-sized maps classified ~every reach `major_river` so every river carved the identical 6.5 m trench). Reaches now spread brook/stream/river/major (default world: 34/37 major → 17 major + 11 river + 9 stream; carve depths 0.98–6.5 m), and the render-path hydrology recompute passes the styled threshold too (was silently diverging whenever `riverDensity` ≠ 1). `RIVER_HALF_MAX` 2.4→3.2 so trunk widths keep differentiating instead of saturating. Carved valleys + channel geometry change everywhere ⇒ discard older autosaves. See prior notes below.
//                                          (prev 76) VOLCANIC IDENTITY + WORLD-DOCTOR SEED CLEANUP: volcanoes get a real identity — a VOLCANIC biome (dark basalt `volcanic_rock` + `ash` tiles) claims scorching mountain-height ground before the alpine Peak/snow branch (`classifyBiome`), the volcano influence lerps temperature to target 0.95 + parches moisture (bare ash flanks, no forest), base cone radius 10→14, and `size` now grows the SUMMIT too (`summitSizeBoost`: huge ⇒ 0.88 ≈ 29 m) — plus an author-facing per-POI `summitM` override for mountain/volcano/glacier. Point-mode climate influences now honour `target` like the region path (oasis/plains points shift slightly). Verdant Vale seed cleaned by the new world doctor (`scripts/probe-world.ts`): Emberpeak `medium`→`huge`, dead `density` fields dropped, the layout-padding-only Cloudwall `region` removed (island layout re-centres), drowned swamp_shrine moved ashore. Biome/tile/elevation output changes everywhere near volcanoes + island layout shifts ⇒ discard older autosaves. See prior notes below.
//                                          (prev 75) PARCEL GRAPH + PARCEL-AWARE WALLS (water parcels, Slice 2): the placer now computes the full `SettlementParcels` graph once (`computeSettlementParcels` in `world/settlement-parcels.ts`) — the HOME bank, the ADJACENT banks in reach, and the short perpendicular water gaps between them (candidate bridges/fords) — and PERSISTS it on the settlement plan (`SettlementPlan.parcels`), the shared spatial model placement/wall/(Slice 3) growth all read. `deriveSettlementRing` now takes the home-bank mask and treats "off the home bank" (water OR far bank) as the AUTHORITATIVE wall boundary — the ring gaps wherever it fronts anything that isn't our own land (`offBank` supersedes the `isWater` ray-sampling in `softGaps`/`waterFrontedSides`/`ensureMainGate`) — so "the wall stays on the home bank / never spans open water" is a guarantee from the model, not a coincidence of heuristics. Falls back to the water heuristic (byte-identical) when no parcel is present (dry inland sites). Persisted plan.parcels + refined ring gaps ⇒ discard older autosaves. See prior notes below.
//                                          (prev 74) SINGLE-BANK SETTLEMENTS (water parcels, Slice 1): building placement is now confined to the settlement's HOME BANK — the land component reachable from the centre without crossing a river (`computeHomeParcel` in `world/settlement-parcels.ts`, a 4-connected non-water flood-fill bounded to radius+8). `fitsAt` (`world/building-placer.ts`) rejects any footprint cell off that bank, so a cluster no longer straddles a river — and the wall, which just encloses the built cluster, follows to one bank for free. Degenerate cases (centre on water, or no water in reach) return null ⇒ no restriction, so dry inland sites stay byte-identical. Root cause: rivers are topographic + settlement-blind (`hydrology.ts`) while placement only rejected footprints ON water, never on the far bank. Design: docs/superpowers/specs/2026-07-01-settlement-water-parcels-design.md (Slices 2–3: per-parcel walls + bridge-gated far-bank wards). New cluster footprints ⇒ discard older autosaves. See prior notes below.
//                                          (prev 73) DIAGONAL TERRAIN-TRACED WALLS: a settlement's defensive ring is no longer an axis-aligned bounding box. `deriveSettlementRing` now traces a star-shaped polygon around the built cluster (`traceRing` in `world/enclosure.ts`): N rays from the town centre each pushed out to enclose the buildings in their sector (+margin, with a half-diagonal floor), then PULLED IN to sit just landward wherever a riverbank/lakeshore/coast lies close outside — so the wall follows the water. Simplified (RDP, ≤14 verts) so a corner drum tower lands only at a real turn. The whole downstream pipeline was already angle-general (chunking rotates each segment to its true bearing, `cornerVertices` detects turns by dot-product, gates/towers yaw to `dir`), so diagonal curtains + corner towers + gates all fall out unchanged. Falls back to the old rectangle when no building footprint is supplied. New ring paths ⇒ discard older autosaves. See prior notes below.
//                                          (prev 72) ROADS LEAD TO GATES: inter-POI approach roads now treat a town's defensive ring as an obstacle (A* can't pierce the curtain except at an opening) and are threaded through each ring's nearest real gate as a road-graph waypoint (`gateApproachPlan` in `world/connectome/gate-approach.ts`), with a `wireGateToRoad` spur backfilling any orphaned gate. The walled-town recipe also DECLARES connectome contracts (`gate.road-connected` + `wall.crossing-only-at-gate`, `world/connectome/wall-contracts.ts`) on `map.contracts`, evaluated by `evaluateContracts`. Road tiles near walls move to the gatehouses ⇒ discard older autosaves. See prior notes below.
//                                          (prev 71) GUARANTEED MAIN GATE: a walled ring that no road actually crosses (the road often just approaches the wall) now gets ONE main gate placed on the landward perimeter point nearest the road (`ensureMainGate`), falling back to the longest landward side's midpoint — so a town is never sealed shut with no way in. Verified in-world (oakshire: one road-gate + water/building gaps). New gate placement ⇒ discard older autosaves. See prior notes below.
//                                          (prev 70) TERRAIN-AWARE DEFENCE + GATE POLICY: `deriveSettlementRing` now classifies each ring SIDE by what lies just outside it — a side fronted by WATER (river bend / lakeshore / coast) is opened entirely (`waterFrontedSides`), so a town is walled only on its approachable landward sides (the water is the wall). And openings are typed (`BarrierGate.kind`): ROAD crossings are real GATES (gatehouse towers + timber leaf + a stair beside), while water/building crossings and the open waterfront are plain GAPS (no gatehouse). Fixes gatehouses sprouting at every crossing; concentrates defence where it's needed. New persisted gate kinds + side-gaps ⇒ discard older autosaves. See prior notes below.
//                                          (prev 69) ENTERABLE TOWERS: a ring's towers now orient to the town (each takes an `inward` vector from the centroid) and carve an arched ENTRANCE DOORWAY on the inner face — you get inside from the courtyard, reached via the mural stairs + wall-walk. Round drums + square gatehouse towers both. Each distinct orientation caches once. (A walk-in cutaway interior, like buildings, is the deferred follow-up for actually seeing the inside.) Render-only, but bump so autosaves regenerate. See prior notes below.
//                                          (prev 68) MURAL STAIRS: a crenellated masonry defensive ring (one that knows its `centroid`, so it knows which side is inner) now grows stone stair flights up to the wall-walk on the INNER face — beside every gate (clear of the passage) + at each long-wall midpoint — via `stairElements` + the new `stair-spec.ts`. A wall is useless if defenders can't man it; this gives access at intervals around the ring. Render-only (composed sprites keyed off the persisted run), but bump so autosaves regenerate with the stairs visible. See prior notes below.
//                                          (prev 67) TIMBER HOARDINGS (hourds): a crenellated masonry town-wall ring now carries `hoarded`, so the curtain grows a wartime TIMBER GALLERY cantilevered out over the OUTER face at parapet level — support beams (putlogs) + overhanging plank floor + shooting breastwork + mono-pitch roof (`hoardingSeg`) — the wooden structure defenders used to drop stones straight down the wall base. The stone merlons are dropped where hoarded (the timber crowns it, as built historically); towers keep theirs. New persisted `BarrierRun.hoarded` ⇒ discard older autosaves. See prior notes below.
//                                          (prev 66) WALLS FACE OUTWARD: a defensive ring now carries its `centroid`, so the masonry cross-section builds the crenellated parapet + merlons on the OUTER (field) edge only, with a low inner kerb closing the wall-walk on the town side — instead of the old centreline coping (thin walls) / symmetric both-edge parapet (thick). `chunkBarrierRun` precomputes a per-chunk `outwardSign` from the centroid. New persisted `BarrierRun.centroid` ⇒ discard older autosaves so walls regenerate facing the right way. See prior notes below.
//                                          (prev 65) LANDFORM MESH PROPS SHELVED: the `buildCoastalLandmarks` pass (sea_arch/cliff_face/cave_mouth/hoodoo mesh props) is disabled in map-generator — the 3D-geometry landform experiment read poorly in-world (billboarding, seams). The generators/part-types/presets stay in the tree unused (re-enable = one line). The HEIGHTFIELD coastal POI features (cliffs/sea_stacks/cove/headland terrain deformation) are UNAFFECTED and still generate. Fewer worldgen entities ⇒ discard older autosaves. See prior notes below.
//                                          (prev 64) LANDMARK KEEP-OUT: coastal/highland landmark props (arch/cliff-face/cave/hoodoo) now keep a 22-tile clearance from settlement seats (`buildCoastalLandmarks` takes settlement centres; `SETTLEMENT_TYPES` = village/city/castle/port/farm/…), so a hoodoo or cave no longer sprouts in the middle of a town. Placement changes ⇒ discard older autosaves. See prior notes below.
//                                          (prev 63) HOODOOS (landforms go INLAND): a fourth natural-landform mesh prop — `hoodoo`, a balanced/mushroom rock: a slender weathered pedestal (thin cylinder + rough rocks) capped by a far wider boulder that overhangs it all round (a pinch a heightfield can't do). `buildCoastalLandmarks` now also dots the rocky HIGHLANDS — `mountain` cells NOT at the water — capped 6, extending landforms beyond the coast. New worldgen entities ⇒ discard older autosaves. See prior notes below.
//                                          (prev 62) SEA CAVES: a third natural-landform mesh prop — `cave_mouth`, a rock hillock with a dark ARCHED RECESS bored into its camera-facing front (partway in, not through: a cave, not a tunnel — the heightfield can't hollow ground). Carved via the `box` prim's aperture + arch head, cloaked in crags. `buildCoastalLandmarks` scatters them on rocky headland BODIES (`mountain`-biome cells at the water), capped 3. New worldgen entities ⇒ discard older autosaves. See prior notes below.
//                                          (prev 61) OVERHANGING CLIFF FACES: a second natural-landform mesh prop — `cliff_face`, a rock brow that leans out PAST its base over the water (an undercut the heightfield can't do; corbel-stack core cloaked in noise-boulder crags, `cliffFacePartType` in parts/landform.ts). `buildCoastalLandmarks` now scatters them on the STEEPEST coasts (`cliff`-biome cells at the water), alongside the sea arches, shared min-spacing, capped 4. New worldgen entities ⇒ discard older autosaves. See prior notes below.
//                                          (prev 60) SEA ARCHES PLACED (first natural-landform MESH prop in the world): worldgen now scatters a few `sea_arch` entities on steep rocky coasts (`buildCoastalLandmarks`, emergent from the biome map, sparse + deterministic, capped 4). A sea arch is a rock ring with a real hole bored through it — a landform the single-valued heightfield physically cannot represent — so it's a generative self-lit mesh prop (`sea_arch` plant preset → composeStructure, no art), foot-z lifted onto the terrain. New worldgen entities ⇒ discard older autosaves. See prior notes below.
//                                          (prev 59) COVES + HEADLANDS (agent-authorable coastal landforms): two more coast-resolved POI types reusing the cliffs infra. `cove` = a land-gated dip carved at the shore so the sea floods IN, biting a sheltered crescent bay with land arms (negative-delta dip + coast anchor; ~100 cells flood land→sea). `headland` = a low green CAPE (plateau mode, gentler: ~8 m brow vs the cliffs' 16 m sheer wall). Demo: "Smuggler's Cove" on the west shore, "Windward Head" on the south. Worldgen elevation changes ⇒ discard older autosaves. See prior notes below.
//                                          (prev 58) SEA STACKS (agent-authorable offshore landform): a new `sea_stacks` POI scatters a seeded cluster of small sharp rocky islets in the water just off a shore anchor (coast-resolved like `cliffs`, stepped seaward, GATED TO SEA so each stack rises isolated from the surf and classifies as bare rock). Demo: "The Drowned Sentinels" off the foot of the Dire Cliffs. New offshore-anchor primitive (`seawardDir`/`placeSeaStacks`). Worldgen elevation changes ⇒ discard older autosaves. See prior notes below.
//                                          (prev 57) DIRE CLIFFS (agent-authorable coastal landform): a new `cliffs` POI raises a flat TABLELAND on the real shore via a new PLATEAU elevation mode (flat top out to `plateauCore`, steep rim, GATED TO LAND so the waterline stays put and the tableland plunges to it in a one-tile sheer face). Anchored seed-proof by a compass `coast` direction (`resolveCoastAnchor`) — never a fixed (x,y) that the seed-varied coastline leaves inland. Demo island gains "The Dire Cliffs" on the east shore: a ~16 m green-topped headland (forest brink, below the 19 m mountain line) plunging to the surf over 30-70 cells, ~75% of the face going rock. Worldgen elevation + tile output change ⇒ discard older autosaves. See prior notes below.
//                                          (prev 56) VERDANT MEADOWS: now that the tile-pick noise is uniformised (v54) and weights are real fractions, `TemperateGrassland` adds a `meadow` (lush light-green) variant WITHOUT starving `hills` — {grass .5, meadow .2, hills .18, dirt .07, scrubland .05}. The Vale's pastures finally read lush (meadow ~5% of land, hills preserved ~6%, grass still dominant ~24%). Tile output changes ⇒ discard older autosaves. See prior notes below.
//                                          (prev 55) VARIED COASTS: the shoreline band is no longer a uniform sandy `Beach` — it sub-types by how steeply the land meets the sea (waterline slopeM): a flat strand stays `Beach` (sand), a tilted one becomes `RockyShore` (rocky/shingle), a steep face a `Cliff` (rock/mountain). Emergent from terrain steepness, applied to EVERY coast (slopeM defaults to 0 → legacy callers still get Beach). Demo island: ~82% beach / ~12% rocky / ~6% cliff; mountainous coasts read as continuous cliff. Coastal tile output changes ⇒ discard older autosaves. See prior notes below.
//                                          (prev 54) TILE-VARIANT WEIGHTS HONOURED: the tile-selection noise (`fbm` octaves:3, ≈Gaussian μ0.5 σ0.085) is now uniformised (Gaussian-CDF remap) before the BIOME_TILES CDF walk, so the weights act as real area fractions instead of starving every band after the first (e.g. forest `glen` clearings 0.01%→~2%, ocean `shallow_water` reaches its 0.4 share, hills/rocky/dirt/scrubland appear at intended density). Monotonic remap ⇒ tile variants still cluster into patches. Every biome's variant MIX shifts (incl. shallow/deep water split) ⇒ discard older autosaves. See prior notes below.
//                                          (prev 53) WALL GATE FIX: the settlement ring bbox now encloses each building's full VISUAL extent (not just its lot tiles), so the curtain sits clear OUTSIDE buildings. Perimeter buildings no longer poke past the line and force a building-wide opening — gates dropped from 10-12 tiles (giant holes) to ~3.8 tiles (real road/water gates). Ring position/gates change ⇒ discard older autosaves. See prior notes below.
//                                          (prev 52) TOWN-WALL THICKNESS: stone town curtain 4 m→2 m (thicknessTiles 2→1) — a typical medieval town wall, not Constantinople-grade. Tall+thin reads as a proper wall; the earthen rampart stays broad. Barrier footprint/foundation carve changes ⇒ discard older autosaves. See prior notes below.
//                                          (prev 51) IRRIGATION REACH: bump the ditch route budget 10→18 tiles (~36 m, a believable canal run) so moderately-near farms connect to water, not just bankside ones (riverside-farm worlds now water ~50-65% of fields; inland-farm worlds stay rain-fed). Ditch tile output changes ⇒ discard older autosaves. See prior notes below.
//                                          (prev 50) IRRIGATION (G7): each farm_field patch within reach of water gets an `irrigation_ditch` conveyance dug across the open soil to the nearest stream/lake, and its served fields are flagged `irrigated`. New tile type + tile output changes ⇒ discard older autosaves. See prior notes below.
//                                          (prev 49) VERDANT VALE REBALANCE: default world `mountainRelief` 95→55. The "massif" tuning + the absolute-metre biome switch had blanketed ~60% of the island's land in mountain/rock; 55 restores a verdant, varied demo island (~7–19% highland, concentrated at the Cloudwall) with the snow-capped peaks still dramatic. Tile output changes ⇒ discard older (rocky) autosaves. See prior notes below.
//                                          (prev 48) FARM FIELDS: farm buildings (barn/stable) now till a patch of `farm_field` tiles on the open soil beyond them — the live noise worldgen had none (farm_field was WFC-only). Walkable ground, so placement/roads unaffected, but tile output changes ⇒ discard older autosaves. See prior notes below.
//                                          (prev 46) RIVER WIDTH TAPER: the painted river raster + the render water mask now stamp at the per-vertex channel width (W ∝ √Q, `reachHalfWidths`) the carve already used — thin spring → broad mouth, stepping up at confluences — instead of a flat per-class halfWidth. River tile footprint changes (walkability/placement) ⇒ discard older autosaves. See prior notes below.
//                                          (prev 45) RIVER DENSITY TUNE: fewer rivers. Base flow threshold 500→560 + headwater taper fraction 0.22→0.40 (shorter wispy headwaters) + `buildWaterNetwork` now uses the same area-scaled+density threshold as the raster (was a fixed 500), so carve widths shrink consistently. New `WorldStyle.riverDensity` knob (default 1 = neutral) scales the threshold INVERSELY through `generateHydrology`/`buildWaterNetwork`. River raster + carved channels change ⇒ discard older autosaves. See prior notes below.
//                                          (prev 44) WALL FOUNDATIONS: worldgen now persists committed barriers on `map.barrierRuns`, and walls/palisades/ramparts carve a stepped `level` footing into the terrain (one gentle brush per ~4-tile span toward the local mean base height) so a curtain crossing a slope sits flush instead of floating. Composed heightfield changes where walls cross grades ⇒ discard older autosaves. See prior notes below.
//                                          (prev 43) ROOMIER WORLD: default island POIs scaled ~1.2× apart (positions + regions + connection waypoints in default.json) and `targetCornerD` lowered 0.7→0.66 so settlements seat centrally with land/coast around them — the cramped central valley spreads out and the island reads a little larger. Tile layout + POI origins + road graph shift ⇒ discard older autosaves. See prior notes below.
//                                          (prev 42) WIDE RIVER RASTER: the river tile raster is widened from the 1-cell D8 centreline to the full connectome channel band (the same disc swath the render mask + carve use), BEFORE settlements + roads site. Buildings no longer land in the visible river and roads bridge the full channel instead of carving dirt across painted water. Tile layout, settlement origins and the road graph all shift ⇒ discard older autosaves. See prior notes below.
//                                          (prev 41) 4-WAY BUILDING ORIENTATION: fill dwellings now rotate (blueprint `orientation` 0..3) to front whichever road their slot faces — placement draws from frontage slots on ALL sides (not just the canonical door side), so settlement layouts (origins, which buildings front which street, the rng stream) shift everywhere. Buildings persist their orientation in the resolved blueprint ⇒ discard older autosaves. See prior notes below.
// 40 = E3 THRESHOLD STOUP: temples/shrines now co-place a holy-water STOUP (cleansing fixture) at their site via the `requires:['cleansing']` token → `stoup` fixtureType → `stoup` prop (E2 fixture co-placement). A new entity at every worship POI ⇒ discard older autosaves. See prior notes below.
// 39 = TEMPLE RETIRED → GENERATIVE (E3 slice 1): temple_small loses its hand preset and expresses via the fold — a deep stone cella (sacred-axial footprint rule) whose footprint VARIES per instance instead of a frozen 3×4 box. Shifts temple geometry/footprint in every temple/shrine POI ⇒ discard older autosaves. See prior notes below.
// 38 = L3b UNDERCROFT + TOWNHOUSE ROSTER: cities now plat burgage TOWNHOUSES (jettied box-frame upper over a stone undercroft base course, L3b) alongside their trades — the city `buildings` roster gains `townhouse` ×3, so which buildings appear shifts. (Pairs with ART v19, the undercroft geometry.) ⇒ discard older autosaves. See prior notes below.
// 37 = FOCI-VILLAGE FILL FIX: the fill spiral (`findPlacement`) is now occupancy-aware — it skips road/civic/claimed cells and returns the first genuinely free spot, instead of returning a road cell (dirt_road/stone_road are BUILDABLE_TERRAIN) that the caller then rejected. A road-dense foci village (church+manor) used to exhaust its placement attempts and stay nearly empty; now it fills its open ground (Oakshire 4→11 buildings with its full roster — manor + smithy/bakehouse/tavern). Shifts every settlement's building layout ⇒ discard older autosaves. See prior notes below.
// 36 = VILLAGE DENSITY: village base buildingCount 3-8→5-10 so a village reads as a real cluster (manor + trades plat even at medium size; a large village bustles ~9-18 yet stays under a large city) instead of a 2-3-building hamlet. Shifts every village's building set ⇒ discard older autosaves. See prior notes below.
// 35 = SETTLEMENT SIZE SCALING: a POI's authored `size` now scales its building count (small 0.7 / medium 1.0 / large 1.8 / huge 2.6) + radius (√scale), so a large village finally musters enough buildings to clear the manor focus rung (focusMin 6) AND round-robin its way to the trades (smithy/tavern/bakehouse) — the E4 roster buildings that previously never landed. Shifts which/how-many buildings every SIZED settlement plats (size-less POIs, e.g. test paths, unchanged). Denser settlements surfaced a latent C1 barrier leak (a slab poking under a building silhouette) — fixed by unifying the settlement-ring gating onto the croft rings' robust slab-midpoint sampling AND filtering `reconcileBarriersWithBuildings` against the building VISUAL extent (not just solid cells), so INV4 holds by construction. ⇒ discard older autosaves. See prior notes below.
// 34 = L2b PER-INSTANCE BUILDING VARIETY: the placer now threads a deterministic per-instance seed (worldSeed ^ poi ^ call-order) into every building synthesis, so each placed instance varies — the generative catalogue→geometry bridge grows its FOOTPRINT from the seed (smithy/inn/bakehouse/brewhouse/granary/dovecote/tithe-barn differ between instances) and gen-form bodies vary their plan length within their lot. Placement stays valid (occupancy-grid reserves whatever footprint results; spatial invariants hold) but differs from v33 ⇒ discard older autosaves. See prior notes below.
// 33 = VERDANT VALE MASSIF: craggy mountain peaks (ridge-noise corrugation in the POI peak), larger mountain influence radius (12→18) + colder cap, a treeline that culls vegetation off bare high ground, Verdant Vale's enlarged/outward-moved mountain region (grows the island), AND a volcano right-sizing — Emberpeak's summit dropped 0.96→0.80 so a cinder cone no longer towers like (or out-snows) the alpine Cloudwall, plus a temperature-gated altitude snowline so only COLD high ground crowns white (a hot desert cone stays bare) — all shift worldgen elevation/biome/entity output ⇒ discard older autosaves. See prior notes below.
// ---- prior WCV notes (kept for history) ----
// 32 = E4 ROSTER SWEEP: villages now plat a smithy + communal bakehouse; towns add an inn, smith, baker and brewer. These catalogue buildingTypes had no pinned geometry preset — they render via the new generative catalogue→fold bridge — so the village/city fill rosters change, shifting which buildings appear (round-robin order) ⇒ worldgen output changes, discard older autosaves. (31 = manor premises stable+well; 30 = site FIXTURES — wells co-placed; 29 = site expansion E2 auxiliaries; 28 = site-fitness live-wiring; 27 = barrier gates over visual extent C1; 26 = diagonal bridges; 25 = riverside levee #24; 24 = parallel-road merge; 23 = entrance stoops; 22 = river density area-scaling; 21 = aqueduct arcade G6 polish; 20 = emergent aqueducts G6 on piers; 19 = stairs CONNECT G3d.)
